compatibility_date = "2026-03-17"
main = "build/cloudflare_worker_example.js"
name = "hello-world"

[build]
command = "just build-dev"
watch_dir = ["src", "cloudflare-worker.d.ts"]

[ai]
binding = "AI"
