#![allow(unused_imports)]
#![allow(clippy::all)]
use super::*;
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = :: js_sys :: Object , js_name = Thang , typescript_type = "Thang")]
    #[derive(Debug, Clone, PartialEq, Eq)]
    #[doc = "The `Thang` class."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub type Thang;
    # [wasm_bindgen (structural , catch , method , getter , js_class = "Thang" , js_name = ok_attr)]
    #[doc = "Getter for the `ok_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/ok_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn ok_attr(this: &Thang) -> Result<i32, JsValue>;
    # [wasm_bindgen (structural , catch , method , setter , js_class = "Thang" , js_name = ok_attr)]
    #[doc = "Setter for the `ok_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/ok_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn set_ok_attr(this: &Thang, value: i32) -> Result<(), JsValue>;
    # [wasm_bindgen (structural , catch , method , getter , js_class = "Thang" , js_name = err_attr)]
    #[doc = "Getter for the `err_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/err_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn err_attr(this: &Thang) -> Result<i32, JsValue>;
    # [wasm_bindgen (structural , catch , method , setter , js_class = "Thang" , js_name = err_attr)]
    #[doc = "Setter for the `err_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/err_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn set_err_attr(this: &Thang, value: i32) -> Result<(), JsValue>;
    # [wasm_bindgen (structural , catch , static_method_of = Thang , getter , js_class = "Thang" , js_name = ok_static_attr)]
    #[doc = "Getter for the `ok_static_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/ok_static_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn ok_static_attr() -> Result<i32, JsValue>;
    # [wasm_bindgen (structural , catch , static_method_of = Thang , setter , js_class = "Thang" , js_name = ok_static_attr)]
    #[doc = "Setter for the `ok_static_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/ok_static_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn set_ok_static_attr(value: i32) -> Result<(), JsValue>;
    # [wasm_bindgen (structural , catch , static_method_of = Thang , getter , js_class = "Thang" , js_name = err_static_attr)]
    #[doc = "Getter for the `err_static_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/err_static_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn err_static_attr() -> Result<i32, JsValue>;
    # [wasm_bindgen (structural , catch , static_method_of = Thang , setter , js_class = "Thang" , js_name = err_static_attr)]
    #[doc = "Setter for the `err_static_attr` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/err_static_attr)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn set_err_static_attr(value: i32) -> Result<(), JsValue>;
    #[wasm_bindgen(catch, constructor, js_class = "Thang")]
    #[doc = "The `new Thang(..)` constructor, creating a new instance of `Thang`."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/Thang)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn new(value: i32) -> Result<Thang, JsValue>;
    # [wasm_bindgen (catch , method , structural , js_class = "Thang" , js_name = err_method)]
    #[doc = "The `err_method()` method."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/err_method)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn err_method(this: &Thang) -> Result<i32, JsValue>;
    # [wasm_bindgen (catch , static_method_of = Thang , js_class = "Thang" , js_name = err_static_method)]
    #[doc = "The `err_static_method()` method."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/err_static_method_static)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn err_static_method() -> Result<i32, JsValue>;
    # [wasm_bindgen (catch , method , structural , js_class = "Thang" , js_name = ok_method)]
    #[doc = "The `ok_method()` method."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/ok_method)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn ok_method(this: &Thang) -> Result<i32, JsValue>;
    # [wasm_bindgen (catch , static_method_of = Thang , js_class = "Thang" , js_name = ok_static_method)]
    #[doc = "The `ok_static_method()` method."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Thang/ok_static_method_static)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Thang`*"]
    pub fn ok_static_method() -> Result<i32, JsValue>;
}
