packages:
  - "*"
catalog:
  "@wasm-tool/wasm-pack-plugin": 1.5.0
  copy-webpack-plugin: ^13.0.1
  cross-env: ^10.0.0
  css-loader: ^6.11.0
  html-webpack-plugin: ^5.6.0
  mini-css-extract-plugin: ^2.9.0
  webpack: ^5.97.0
  webpack-cli: ^5.1.4
  webpack-dev-server: ^5.0.4
