(module $anyref_import_catch_reftest.wasm
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func (param i32)))
  (type (;2;) (func (result i32 i32)))
  (type (;3;) (func (result i32)))
  (type (;4;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c75d47bf9e7731e" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_foo_fb65c8eea1052a08" (func (;1;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;2;) (type 4)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $"exported multivalue shim"))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_dealloc" (func $__externref_table_dealloc))
  (export "__wbindgen_start" (func 2))
  (func $"exported multivalue shim" (;3;) (type 2) (result i32 i32))
  (func $__wbindgen_exn_store (;4;) (type 1) (param i32))
  (func $__externref_table_alloc (;5;) (type 3) (result i32))
  (func $__externref_table_dealloc (;6;) (type 1) (param i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
