(module $arg_name_collision_reftest.wasm
  (type (;0;) (func (param f64 i32) (result f64)))
  (type (;1;) (func (param i32 i32 i32 i32) (result i32 i32)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32) (result i32 i32)))
  (type (;4;) (func (param i32 i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32)))
  (type (;7;) (func (param i32) (result i32)))
  (type (;8;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_5d9e815e6fdf150f" (func (;0;) (type 6)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 8)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "class_arg" (func $class_arg))
  (export "foo_add" (func $foo_add))
  (export "foo_consume" (func $foo_consume))
  (export "foo_new" (func $foo_new))
  (export "global_args" (func $global_args))
  (export "local_args" (func $"local_args multivalue shim"))
  (export "wasm_args" (func $"wasm_args multivalue shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_foo_free (;2;) (type 6) (param i32 i32))
  (func $class_arg (;3;) (type 7) (param i32) (result i32))
  (func $foo_add (;4;) (type 5) (param i32 i32) (result i32))
  (func $foo_consume (;5;) (type 5) (param i32 i32) (result i32))
  (func $foo_new (;6;) (type 7) (param i32) (result i32))
  (func $global_args (;7;) (type 0) (param f64 i32) (result f64))
  (func $"local_args multivalue shim" (;8;) (type 1) (param i32 i32 i32 i32) (result i32 i32))
  (func $"wasm_args multivalue shim" (;9;) (type 3) (param i32 i32 i32) (result i32 i32))
  (func $__wbindgen_malloc (;10;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;11;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;12;) (type 4) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
