(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32) (result externref)))
  (type (;7;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;8;) (func (param i32 i32 externref)))
  (type (;9;) (func (param i32 i32 externref externref)))
  (type (;10;) (func (param i32 externref)))
  (type (;11;) (func (param externref)))
  (type (;12;) (func (param externref) (result i32)))
  (type (;13;) (func (param externref) (result externref)))
  (type (;14;) (func (param externref externref) (result externref)))
  (type (;15;) (func (param externref externref externref) (result externref)))
  (import "./reference_test_bg.js" "__wbg_call_52af042a326d9b3a" (func (;0;) (type 15)))
  (import "./reference_test_bg.js" "__wbg_call_90bf4b9978d51034" (func (;1;) (type 14)))
  (import "./reference_test_bg.js" "__wbg_new_b38cbb8a106768cf" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_newnoargs_863941679b1933bb" (func (;3;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_queueMicrotask_1d75ffff194a09bc" (func (;4;) (type 11)))
  (import "./reference_test_bg.js" "__wbg_queueMicrotask_b9a8d325fc1ebe35" (func (;5;) (type 13)))
  (import "./reference_test_bg.js" "__wbg_resolve_f9faa06f9350ac82" (func (;6;) (type 13)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_GLOBAL_656a564fb01c5b63" (func (;7;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_GLOBAL_THIS_09a6cc4b9571ef65" (func (;8;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_SELF_36742aea97854d74" (func (;9;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_WINDOW_0ce0d90b0830e7e6" (func (;10;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_then_66350f316a20107b" (func (;11;) (type 14)))
  (import "./reference_test_bg.js" "__wbg_wbindgencbdrop_470850fcb28f4519" (func (;12;) (type 12)))
  (import "./reference_test_bg.js" "__wbg_wbindgendebugstring_0c28a61befa1f3ce" (func (;13;) (type 10)))
  (import "./reference_test_bg.js" "__wbg_wbindgenisfunction_27a5c72d80bbdf07" (func (;14;) (type 12)))
  (import "./reference_test_bg.js" "__wbg_wbindgenisundefined_2e902cd900cf5927" (func (;15;) (type 12)))
  (import "./reference_test_bg.js" "__wbg_wbindgenthrow_681185b504fabc8e" (func (;16;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_cast_3d26b1bba51b9b88" (func (;17;) (type 6)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;18;) (type 0)))
  (func $"foo externref shim" (;19;) (type 2) (result externref))
  (func $__wbindgen_exn_store (;20;) (type 3) (param i32))
  (func $__externref_table_alloc (;21;) (type 1) (result i32))
  (func $__wbindgen_malloc (;22;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;23;) (type 7) (param i32 i32 i32 i32) (result i32))
  (func $"closure17 externref shim" (;24;) (type 8) (param i32 i32 externref))
  (func $"closure19 externref shim" (;25;) (type 9) (param i32 i32 externref externref))
  (table (;0;) 74 74 funcref)
  (table (;1;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "foo" (func $"foo externref shim"))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_export_2" (table 1))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_export_5" (table 0))
  (export "closure17_externref_shim" (func $"closure17 externref shim"))
  (export "closure19_externref_shim" (func $"closure19 externref shim"))
  (export "__wbindgen_start" (func 18))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
