(module $custom_section_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32 i32)))
  (type (;2;) (func (param i32 i32 i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "test_function" (func $"test_function multivalue shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 0))
  (func $"test_function multivalue shim" (;1;) (type 1) (result i32 i32))
  (func $__wbindgen_free (;2;) (type 2) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
