(module $discriminated_union_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32) (result externref)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32) (result externref)))
  (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;7;) (func (param i32 externref)))
  (type (;8;) (func (param externref) (result i32)))
  (type (;9;) (func (param externref) (result externref)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_string_get_e4f06c90489ad01b" (func (;0;) (type 7)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_b855445ff6a94295" (func (;1;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_exportedstruct_new" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_exportedstruct_unwrap" (func (;3;) (type 8)))
  (import "./reference_test_bg.js" "__wbg_instanceof_ImportedType_a80b21e205d50507" (func (;4;) (type 8)))
  (import "./reference_test_bg.js" "__wbindgen_cast_0000000000000000" (func (;5;) (type 5)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;6;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_exportedstruct_free" (func $__wbg_exportedstruct_free))
  (export "echo_response" (func $"echo_response externref shim"))
  (export "echo_status" (func $"echo_status externref shim"))
  (export "exportedstruct_new" (func $exportedstruct_new))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 6))
  (func $__wbg_exportedstruct_free (;7;) (type 3) (param i32 i32))
  (func $"echo_response externref shim" (;8;) (type 9) (param externref) (result externref))
  (func $"echo_status externref shim" (;9;) (type 9) (param externref) (result externref))
  (func $exportedstruct_new (;10;) (type 1) (param i32) (result i32))
  (func $__wbindgen_malloc (;11;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;12;) (type 6) (param i32 i32 i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
