(module $dynamic_union_reftest.wasm
  (type (;0;) (func (param externref) (result externref)))
  (type (;1;) (func (param externref) (result i32)))
  (type (;2;) (func (param i32 externref)))
  (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;4;) (func (param i32 i32) (result externref)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32)))
  (type (;7;) (func (param i32) (result externref)))
  (type (;8;) (func (param i32) (result i32)))
  (type (;9;) (func (result i32)))
  (type (;10;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_is_undefined_67b456be8673d3d7" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_string_get_72bdf95d3ae505b1" (func (;1;) (type 2)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_1506f2235d1bdba0" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_exportedstruct_new" (func (;3;) (type 7)))
  (import "./reference_test_bg.js" "__wbg_exportedstruct_unwrap" (func (;4;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_instanceof_ImportedType_fe5eedffdd3920ad" (func (;5;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_cast_0000000000000000" (func (;6;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;7;) (type 10)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_exportedstruct_free" (func $__wbg_exportedstruct_free))
  (export "echo_fallback" (func $"echo_fallback externref shim"))
  (export "echo_optional_wrapper" (func $"echo_optional_wrapper externref shim"))
  (export "echo_response" (func $"echo_response externref shim"))
  (export "echo_status" (func $"echo_status externref shim"))
  (export "echo_wrapper" (func $"echo_wrapper externref shim"))
  (export "exportedstruct_new" (func $exportedstruct_new))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_start" (func 7))
  (func $__wbg_exportedstruct_free (;8;) (type 6) (param i32 i32))
  (func $"echo_fallback externref shim" (;9;) (type 0) (param externref) (result externref))
  (func $"echo_optional_wrapper externref shim" (;10;) (type 7) (param i32) (result externref))
  (func $"echo_response externref shim" (;11;) (type 0) (param externref) (result externref))
  (func $"echo_status externref shim" (;12;) (type 0) (param externref) (result externref))
  (func $"echo_wrapper externref shim" (;13;) (type 0) (param externref) (result externref))
  (func $exportedstruct_new (;14;) (type 8) (param i32) (result i32))
  (func $__wbindgen_malloc (;15;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;16;) (type 3) (param i32 i32 i32 i32) (result i32))
  (func $__externref_table_alloc (;17;) (type 9) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
