(module $echo_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func (param i32) (result externref)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32) (result i32 i32)))
  (type (;7;) (func (param i32 i32) (result externref)))
  (type (;8;) (func (param i32 i32 i32)))
  (type (;9;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;10;) (func (param i32 i64) (result i32 i64)))
  (type (;11;) (func (param i32 i64 i64) (result i32 i64 i64)))
  (type (;12;) (func (param i32 f64) (result i32 f64)))
  (type (;13;) (func (param i32 externref)))
  (type (;14;) (func (param i64) (result i64)))
  (type (;15;) (func (param i64 i64) (result i64 i64)))
  (type (;16;) (func (param f32) (result f32)))
  (type (;17;) (func (param f64) (result f64)))
  (type (;18;) (func (param externref) (result i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_46569e04243a7370" (func (;0;) (type 13)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_string_get_e935d22db323c682" (func (;1;) (type 13)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_f1861aae416df39d" (func (;2;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_foo_new" (func (;3;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_foo_unwrap" (func (;4;) (type 18)))
  (import "./reference_test_bg.js" "__wbindgen_cast_0000000000000000" (func (;5;) (type 7)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;6;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "echo_bool" (func $echo_bool))
  (export "echo_char" (func $echo_char))
  (export "echo_f32" (func $echo_f32))
  (export "echo_f64" (func $echo_f64))
  (export "echo_i128" (func $"echo_i128 multivalue shim"))
  (export "echo_i16" (func $echo_i16))
  (export "echo_i32" (func $echo_i32))
  (export "echo_i64" (func $echo_i64))
  (export "echo_i8" (func $echo_i8))
  (export "echo_isize" (func $echo_isize))
  (export "echo_option_bool" (func $echo_option_bool))
  (export "echo_option_char" (func $echo_option_char))
  (export "echo_option_f32" (func $echo_option_f32))
  (export "echo_option_f64" (func $"echo_option_f64 multivalue shim"))
  (export "echo_option_i128" (func $"echo_option_i128 multivalue shim"))
  (export "echo_option_i16" (func $echo_option_i16))
  (export "echo_option_i32" (func $echo_option_i32))
  (export "echo_option_i64" (func $"echo_option_i64 multivalue shim"))
  (export "echo_option_i8" (func $echo_option_i8))
  (export "echo_option_isize" (func $echo_option_isize))
  (export "echo_option_string" (func $"echo_option_string multivalue shim"))
  (export "echo_option_struct" (func $echo_option_struct))
  (export "echo_option_u128" (func $"echo_option_u128 multivalue shim"))
  (export "echo_option_u16" (func $echo_option_u16))
  (export "echo_option_u32" (func $echo_option_u32))
  (export "echo_option_u64" (func $"echo_option_u64 multivalue shim"))
  (export "echo_option_u8" (func $echo_option_u8))
  (export "echo_option_usize" (func $echo_option_usize))
  (export "echo_option_vec_i16" (func $"echo_option_vec_i16 multivalue shim"))
  (export "echo_option_vec_i32" (func $"echo_option_vec_i32 multivalue shim"))
  (export "echo_option_vec_i64" (func $"echo_option_vec_i64 multivalue shim"))
  (export "echo_option_vec_i8" (func $"echo_option_vec_i8 multivalue shim"))
  (export "echo_option_vec_string" (func $"echo_option_vec_string multivalue shim"))
  (export "echo_option_vec_struct" (func $"echo_option_vec_struct multivalue shim"))
  (export "echo_option_vec_u16" (func $"echo_option_vec_u16 multivalue shim"))
  (export "echo_option_vec_u32" (func $"echo_option_vec_u32 multivalue shim"))
  (export "echo_option_vec_u64" (func $"echo_option_vec_u64 multivalue shim"))
  (export "echo_option_vec_u8" (func $"echo_option_vec_u8 multivalue shim"))
  (export "echo_option_vec_uninit_i16" (func $"echo_option_vec_uninit_i16 multivalue shim"))
  (export "echo_option_vec_uninit_i32" (func $"echo_option_vec_uninit_i32 multivalue shim"))
  (export "echo_option_vec_uninit_i64" (func $"echo_option_vec_uninit_i64 multivalue shim"))
  (export "echo_option_vec_uninit_i8" (func $"echo_option_vec_uninit_i8 multivalue shim"))
  (export "echo_option_vec_uninit_u16" (func $"echo_option_vec_uninit_u16 multivalue shim"))
  (export "echo_option_vec_uninit_u32" (func $"echo_option_vec_uninit_u32 multivalue shim"))
  (export "echo_option_vec_uninit_u64" (func $"echo_option_vec_uninit_u64 multivalue shim"))
  (export "echo_option_vec_uninit_u8" (func $"echo_option_vec_uninit_u8 multivalue shim"))
  (export "echo_string" (func $"echo_string multivalue shim"))
  (export "echo_struct" (func $echo_struct))
  (export "echo_u128" (func $"echo_u128 multivalue shim"))
  (export "echo_u16" (func $echo_u16))
  (export "echo_u32" (func $echo_u32))
  (export "echo_u64" (func $echo_u64))
  (export "echo_u8" (func $echo_u8))
  (export "echo_usize" (func $echo_usize))
  (export "echo_vec_i16" (func $"echo_vec_i16 multivalue shim"))
  (export "echo_vec_i32" (func $"echo_vec_i32 multivalue shim"))
  (export "echo_vec_i64" (func $"echo_vec_i64 multivalue shim"))
  (export "echo_vec_i8" (func $"echo_vec_i8 multivalue shim"))
  (export "echo_vec_string" (func $"echo_vec_string multivalue shim"))
  (export "echo_vec_struct" (func $"echo_vec_struct multivalue shim"))
  (export "echo_vec_u16" (func $"echo_vec_u16 multivalue shim"))
  (export "echo_vec_u32" (func $"echo_vec_u32 multivalue shim"))
  (export "echo_vec_u64" (func $"echo_vec_u64 multivalue shim"))
  (export "echo_vec_u8" (func $"echo_vec_u8 multivalue shim"))
  (export "echo_vec_uninit_i16" (func $"echo_vec_uninit_i16 multivalue shim"))
  (export "echo_vec_uninit_i32" (func $"echo_vec_uninit_i32 multivalue shim"))
  (export "echo_vec_uninit_i64" (func $"echo_vec_uninit_i64 multivalue shim"))
  (export "echo_vec_uninit_i8" (func $"echo_vec_uninit_i8 multivalue shim"))
  (export "echo_vec_uninit_u16" (func $"echo_vec_uninit_u16 multivalue shim"))
  (export "echo_vec_uninit_u32" (func $"echo_vec_uninit_u32 multivalue shim"))
  (export "echo_vec_uninit_u64" (func $"echo_vec_uninit_u64 multivalue shim"))
  (export "echo_vec_uninit_u8" (func $"echo_vec_uninit_u8 multivalue shim"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__wbindgen_start" (func 6))
  (func $__wbg_foo_free (;7;) (type 4) (param i32 i32))
  (func $echo_bool (;8;) (type 2) (param i32) (result i32))
  (func $echo_char (;9;) (type 2) (param i32) (result i32))
  (func $echo_f32 (;10;) (type 16) (param f32) (result f32))
  (func $echo_f64 (;11;) (type 17) (param f64) (result f64))
  (func $"echo_i128 multivalue shim" (;12;) (type 15) (param i64 i64) (result i64 i64))
  (func $echo_i16 (;13;) (type 2) (param i32) (result i32))
  (func $echo_i32 (;14;) (type 2) (param i32) (result i32))
  (func $echo_i64 (;15;) (type 14) (param i64) (result i64))
  (func $echo_i8 (;16;) (type 2) (param i32) (result i32))
  (func $echo_isize (;17;) (type 2) (param i32) (result i32))
  (func $echo_option_bool (;18;) (type 2) (param i32) (result i32))
  (func $echo_option_char (;19;) (type 2) (param i32) (result i32))
  (func $echo_option_f32 (;20;) (type 17) (param f64) (result f64))
  (func $"echo_option_f64 multivalue shim" (;21;) (type 12) (param i32 f64) (result i32 f64))
  (func $"echo_option_i128 multivalue shim" (;22;) (type 11) (param i32 i64 i64) (result i32 i64 i64))
  (func $echo_option_i16 (;23;) (type 2) (param i32) (result i32))
  (func $echo_option_i32 (;24;) (type 17) (param f64) (result f64))
  (func $"echo_option_i64 multivalue shim" (;25;) (type 10) (param i32 i64) (result i32 i64))
  (func $echo_option_i8 (;26;) (type 2) (param i32) (result i32))
  (func $echo_option_isize (;27;) (type 17) (param f64) (result f64))
  (func $"echo_option_string multivalue shim" (;28;) (type 6) (param i32 i32) (result i32 i32))
  (func $echo_option_struct (;29;) (type 2) (param i32) (result i32))
  (func $"echo_option_u128 multivalue shim" (;30;) (type 11) (param i32 i64 i64) (result i32 i64 i64))
  (func $echo_option_u16 (;31;) (type 2) (param i32) (result i32))
  (func $echo_option_u32 (;32;) (type 17) (param f64) (result f64))
  (func $"echo_option_u64 multivalue shim" (;33;) (type 10) (param i32 i64) (result i32 i64))
  (func $echo_option_u8 (;34;) (type 2) (param i32) (result i32))
  (func $echo_option_usize (;35;) (type 17) (param f64) (result f64))
  (func $"echo_option_vec_i16 multivalue shim" (;36;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i32 multivalue shim" (;37;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i64 multivalue shim" (;38;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_i8 multivalue shim" (;39;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_string multivalue shim" (;40;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_struct multivalue shim" (;41;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u16 multivalue shim" (;42;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u32 multivalue shim" (;43;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u64 multivalue shim" (;44;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_u8 multivalue shim" (;45;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i16 multivalue shim" (;46;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i32 multivalue shim" (;47;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i64 multivalue shim" (;48;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_i8 multivalue shim" (;49;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u16 multivalue shim" (;50;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u32 multivalue shim" (;51;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u64 multivalue shim" (;52;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_option_vec_uninit_u8 multivalue shim" (;53;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_string multivalue shim" (;54;) (type 6) (param i32 i32) (result i32 i32))
  (func $echo_struct (;55;) (type 2) (param i32) (result i32))
  (func $"echo_u128 multivalue shim" (;56;) (type 15) (param i64 i64) (result i64 i64))
  (func $echo_u16 (;57;) (type 2) (param i32) (result i32))
  (func $echo_u32 (;58;) (type 2) (param i32) (result i32))
  (func $echo_u64 (;59;) (type 14) (param i64) (result i64))
  (func $echo_u8 (;60;) (type 2) (param i32) (result i32))
  (func $echo_usize (;61;) (type 2) (param i32) (result i32))
  (func $"echo_vec_i16 multivalue shim" (;62;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i32 multivalue shim" (;63;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i64 multivalue shim" (;64;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_i8 multivalue shim" (;65;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_string multivalue shim" (;66;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_struct multivalue shim" (;67;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u16 multivalue shim" (;68;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u32 multivalue shim" (;69;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u64 multivalue shim" (;70;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_u8 multivalue shim" (;71;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i16 multivalue shim" (;72;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i32 multivalue shim" (;73;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i64 multivalue shim" (;74;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_i8 multivalue shim" (;75;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u16 multivalue shim" (;76;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u32 multivalue shim" (;77;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u64 multivalue shim" (;78;) (type 6) (param i32 i32) (result i32 i32))
  (func $"echo_vec_uninit_u8 multivalue shim" (;79;) (type 6) (param i32 i32) (result i32 i32))
  (func $__wbindgen_malloc (;80;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;81;) (type 9) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;82;) (type 8) (param i32 i32 i32))
  (func $__externref_table_alloc (;83;) (type 1) (result i32))
  (func $__externref_drop_slice (;84;) (type 4) (param i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
