(module $enum_vec_reftest.wasm
  (type (;0;) (func (param f64) (result externref)))
  (type (;1;) (func (param i32 externref)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32)))
  (type (;4;) (func (param i32 i32) (result i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32)))
  (type (;7;) (func (result i32)))
  (type (;8;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_a57024b9c6e4a48b" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_number_get_136b9679cab35cfb" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_bb96b2010945f0bc" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbindgen_generic_0000000000000000" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;4;) (type 8)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "enum_vec_echo" (func $"enum_vec_echo multivalue shim"))
  (export "hidden_err_vec_echo" (func $"hidden_err_vec_echo multivalue shim"))
  (export "ns_err_vec_echo" (func $"ns_err_vec_echo multivalue shim"))
  (export "option_enum_vec_echo" (func $"option_enum_vec_echo multivalue shim"))
  (export "renamed_err_vec_echo" (func $"renamed_err_vec_echo multivalue shim"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 4))
  (func $"enum_vec_echo multivalue shim" (;5;) (type 4) (param i32 i32) (result i32 i32))
  (func $"hidden_err_vec_echo multivalue shim" (;6;) (type 4) (param i32 i32) (result i32 i32))
  (func $"ns_err_vec_echo multivalue shim" (;7;) (type 4) (param i32 i32) (result i32 i32))
  (func $"option_enum_vec_echo multivalue shim" (;8;) (type 4) (param i32 i32) (result i32 i32))
  (func $"renamed_err_vec_echo multivalue shim" (;9;) (type 4) (param i32 i32) (result i32 i32))
  (func $__wbindgen_malloc (;10;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;11;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func $__externref_table_alloc (;12;) (type 7) (result i32))
  (func $__externref_drop_slice (;13;) (type 6) (param i32 i32))
  (func $__wbindgen_free (;14;) (type 3) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
