(module $enums_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_dd24417ed36fc46e" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "enum_echo" (func $enum_echo))
  (export "option_enum_echo" (func $option_enum_echo))
  (export "get_name" (func $get_name))
  (export "option_string_enum_echo" (func $option_string_enum_echo))
  (export "option_order" (func $option_order))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $enum_echo (;2;) (type 1) (param i32) (result i32))
  (func $option_enum_echo (;3;) (type 1) (param i32) (result i32))
  (func $get_name (;4;) (type 1) (param i32) (result i32))
  (func $option_string_enum_echo (;5;) (type 1) (param i32) (result i32))
  (func $option_order (;6;) (type 1) (param i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
