(module $exported_class_wrap_matrix_reftest.wasm
  (type (;0;) (func (param i32 i32) (result externref)))
  (type (;1;) (func (param i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32) (result externref)))
  (type (;4;) (func (param i32) (result i32)))
  (type (;5;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c31b086c2b26051" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_animal_new" (func (;1;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_car_new" (func (;2;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_dog_new" (func (;3;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_garden__derived_new" (func (;4;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_nsa__widget_new" (func (;5;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_reserve_new" (func (;6;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_vehicle_new" (func (;7;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_wild__habitat_new" (func (;8;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_zoo__base_new" (func (;9;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;10;) (type 5)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_animal_free" (func $__wbg_animal_free))
  (export "__wbg_car_free" (func $__wbg_car_free))
  (export "__wbg_dog_free" (func $__wbg_dog_free))
  (export "__wbg_garden__derived_free" (func $__wbg_garden__derived_free))
  (export "__wbg_nsa__widget_free" (func $__wbg_nsa__widget_free))
  (export "__wbg_reserve_free" (func $__wbg_reserve_free))
  (export "__wbg_upcast_car_to_vehicle" (func $__wbg_upcast_car_to_vehicle))
  (export "__wbg_upcast_dog_to_animal" (func $__wbg_upcast_dog_to_animal))
  (export "__wbg_upcast_garden__derived_to_zoo__base" (func $__wbg_upcast_garden__derived_to_zoo__base))
  (export "__wbg_upcast_reserve_to_wild__habitat" (func $__wbg_upcast_reserve_to_wild__habitat))
  (export "__wbg_vehicle_free" (func $__wbg_vehicle_free))
  (export "__wbg_wild__habitat_free" (func $__wbg_wild__habitat_free))
  (export "__wbg_zoo__base_free" (func $__wbg_zoo__base_free))
  (export "animal_legs" (func $animal_legs))
  (export "animal_new" (func $animal_new))
  (export "car_doors" (func $car_doors))
  (export "car_new" (func $car_new))
  (export "dog_breed" (func $dog_breed))
  (export "dog_new" (func $dog_new))
  (export "garden__derived_new" (func $garden__derived_new))
  (export "garden__derived_tag" (func $garden__derived_tag))
  (export "makeAnimal" (func $"makeAnimal externref shim"))
  (export "makeBase" (func $"makeBase externref shim"))
  (export "makeCar" (func $"makeCar externref shim"))
  (export "makeDerived" (func $"makeDerived externref shim"))
  (export "makeDog" (func $"makeDog externref shim"))
  (export "makeHabitat" (func $"makeHabitat externref shim"))
  (export "makeReserve" (func $"makeReserve externref shim"))
  (export "makeVehicle" (func $"makeVehicle externref shim"))
  (export "makeWidget" (func $"makeWidget externref shim"))
  (export "nsa__widget_new" (func $nsa__widget_new))
  (export "nsa__widget_v" (func $nsa__widget_v))
  (export "readDog" (func $readDog))
  (export "readWidget" (func $readWidget))
  (export "reserve_new" (func $reserve_new))
  (export "reserve_rangers" (func $reserve_rangers))
  (export "vehicle_new" (func $vehicle_new))
  (export "vehicle_wheels" (func $vehicle_wheels))
  (export "wild__habitat_area" (func $wild__habitat_area))
  (export "wild__habitat_new" (func $wild__habitat_new))
  (export "zoo__base_id" (func $zoo__base_id))
  (export "zoo__base_new" (func $zoo__base_new))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 10))
  (func $__wbg_animal_free (;11;) (type 2) (param i32 i32))
  (func $__wbg_car_free (;12;) (type 2) (param i32 i32))
  (func $__wbg_dog_free (;13;) (type 2) (param i32 i32))
  (func $__wbg_garden__derived_free (;14;) (type 2) (param i32 i32))
  (func $__wbg_nsa__widget_free (;15;) (type 2) (param i32 i32))
  (func $__wbg_reserve_free (;16;) (type 2) (param i32 i32))
  (func $__wbg_upcast_car_to_vehicle (;17;) (type 4) (param i32) (result i32))
  (func $__wbg_upcast_dog_to_animal (;18;) (type 4) (param i32) (result i32))
  (func $__wbg_upcast_garden__derived_to_zoo__base (;19;) (type 4) (param i32) (result i32))
  (func $__wbg_upcast_reserve_to_wild__habitat (;20;) (type 4) (param i32) (result i32))
  (func $__wbg_vehicle_free (;21;) (type 2) (param i32 i32))
  (func $__wbg_wild__habitat_free (;22;) (type 2) (param i32 i32))
  (func $__wbg_zoo__base_free (;23;) (type 2) (param i32 i32))
  (func $animal_legs (;24;) (type 4) (param i32) (result i32))
  (func $animal_new (;25;) (type 4) (param i32) (result i32))
  (func $car_doors (;26;) (type 4) (param i32) (result i32))
  (func $car_new (;27;) (type 1) (param i32 i32) (result i32))
  (func $dog_breed (;28;) (type 4) (param i32) (result i32))
  (func $dog_new (;29;) (type 1) (param i32 i32) (result i32))
  (func $garden__derived_new (;30;) (type 1) (param i32 i32) (result i32))
  (func $garden__derived_tag (;31;) (type 4) (param i32) (result i32))
  (func $"makeAnimal externref shim" (;32;) (type 3) (param i32) (result externref))
  (func $"makeBase externref shim" (;33;) (type 3) (param i32) (result externref))
  (func $"makeCar externref shim" (;34;) (type 0) (param i32 i32) (result externref))
  (func $"makeDerived externref shim" (;35;) (type 0) (param i32 i32) (result externref))
  (func $"makeDog externref shim" (;36;) (type 0) (param i32 i32) (result externref))
  (func $"makeHabitat externref shim" (;37;) (type 3) (param i32) (result externref))
  (func $"makeReserve externref shim" (;38;) (type 0) (param i32 i32) (result externref))
  (func $"makeVehicle externref shim" (;39;) (type 3) (param i32) (result externref))
  (func $"makeWidget externref shim" (;40;) (type 3) (param i32) (result externref))
  (func $nsa__widget_new (;41;) (type 4) (param i32) (result i32))
  (func $nsa__widget_v (;42;) (type 4) (param i32) (result i32))
  (func $readDog (;43;) (type 4) (param i32) (result i32))
  (func $readWidget (;44;) (type 4) (param i32) (result i32))
  (func $reserve_new (;45;) (type 1) (param i32 i32) (result i32))
  (func $reserve_rangers (;46;) (type 4) (param i32) (result i32))
  (func $vehicle_new (;47;) (type 4) (param i32) (result i32))
  (func $vehicle_wheels (;48;) (type 4) (param i32) (result i32))
  (func $wild__habitat_area (;49;) (type 4) (param i32) (result i32))
  (func $wild__habitat_new (;50;) (type 4) (param i32) (result i32))
  (func $zoo__base_id (;51;) (type 4) (param i32) (result i32))
  (func $zoo__base_new (;52;) (type 4) (param i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
