(module $exported_class_wrap_matrix_reftest.wasm
  (type (;0;) (func (param externref) (result i32)))
  (type (;1;) (func (param i32 externref)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32) (result externref)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32)))
  (type (;6;) (func (param i32) (result externref)))
  (type (;7;) (func (param i32) (result i32)))
  (type (;8;) (func (result i32)))
  (type (;9;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_c25b10b7971b60c3" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_ccc13625347c7d2e" (func (;1;) (type 5)))
  (import "./reference_test_bg.js" "__wbg_animal_new" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_animal_unwrap" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_car_new" (func (;4;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_car_unwrap" (func (;5;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_dog_new" (func (;6;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_dog_unwrap" (func (;7;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_garden__derived_new" (func (;8;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_garden__derived_unwrap" (func (;9;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_nsa__widget_new" (func (;10;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_nsa__widget_unwrap" (func (;11;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_reserve_new" (func (;12;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_reserve_unwrap" (func (;13;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_vehicle_new" (func (;14;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_vehicle_unwrap" (func (;15;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_wild__habitat_new" (func (;16;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_wild__habitat_unwrap" (func (;17;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_zoo__base_new" (func (;18;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_zoo__base_unwrap" (func (;19;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;20;) (type 9)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_animal_free" (func $__wbg_animal_free))
  (export "__wbg_car_free" (func $__wbg_car_free))
  (export "__wbg_dog_free" (func $__wbg_dog_free))
  (export "__wbg_garden__derived_free" (func $__wbg_garden__derived_free))
  (export "__wbg_nsa__widget_free" (func $__wbg_nsa__widget_free))
  (export "__wbg_reserve_free" (func $__wbg_reserve_free))
  (export "__wbg_upcast_car_to_vehicle" (func $__wbg_upcast_car_to_vehicle))
  (export "__wbg_upcast_dog_to_animal" (func $__wbg_upcast_dog_to_animal))
  (export "__wbg_upcast_garden__derived_to_zoo__base" (func $__wbg_upcast_garden__derived_to_zoo__base))
  (export "__wbg_upcast_reserve_to_wild__habitat" (func $__wbg_upcast_reserve_to_wild__habitat))
  (export "__wbg_vehicle_free" (func $__wbg_vehicle_free))
  (export "__wbg_wild__habitat_free" (func $__wbg_wild__habitat_free))
  (export "__wbg_zoo__base_free" (func $__wbg_zoo__base_free))
  (export "animal_legs" (func $animal_legs))
  (export "animal_new" (func $animal_new))
  (export "car_doors" (func $car_doors))
  (export "car_new" (func $car_new))
  (export "dog_breed" (func $dog_breed))
  (export "dog_new" (func $dog_new))
  (export "garden__derived_new" (func $garden__derived_new))
  (export "garden__derived_tag" (func $garden__derived_tag))
  (export "makeAnimal" (func $"makeAnimal externref shim"))
  (export "makeBase" (func $"makeBase externref shim"))
  (export "makeCar" (func $"makeCar externref shim"))
  (export "makeDerived" (func $"makeDerived externref shim"))
  (export "makeDog" (func $"makeDog externref shim"))
  (export "makeHabitat" (func $"makeHabitat externref shim"))
  (export "makeReserve" (func $"makeReserve externref shim"))
  (export "makeVehicle" (func $"makeVehicle externref shim"))
  (export "makeWidget" (func $"makeWidget externref shim"))
  (export "nsa__widget_new" (func $nsa__widget_new))
  (export "nsa__widget_v" (func $nsa__widget_v))
  (export "readAnimals" (func $readAnimals))
  (export "readBases" (func $readBases))
  (export "readCars" (func $readCars))
  (export "readDeriveds" (func $readDeriveds))
  (export "readDog" (func $readDog))
  (export "readDogs" (func $readDogs))
  (export "readHabitats" (func $readHabitats))
  (export "readReserves" (func $readReserves))
  (export "readVehicles" (func $readVehicles))
  (export "readWidget" (func $readWidget))
  (export "readWidgets" (func $readWidgets))
  (export "reserve_new" (func $reserve_new))
  (export "reserve_rangers" (func $reserve_rangers))
  (export "vehicle_new" (func $vehicle_new))
  (export "vehicle_wheels" (func $vehicle_wheels))
  (export "wild__habitat_area" (func $wild__habitat_area))
  (export "wild__habitat_new" (func $wild__habitat_new))
  (export "zoo__base_id" (func $zoo__base_id))
  (export "zoo__base_new" (func $zoo__base_new))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_start" (func 20))
  (func $__wbg_animal_free (;21;) (type 5) (param i32 i32))
  (func $__wbg_car_free (;22;) (type 5) (param i32 i32))
  (func $__wbg_dog_free (;23;) (type 5) (param i32 i32))
  (func $__wbg_garden__derived_free (;24;) (type 5) (param i32 i32))
  (func $__wbg_nsa__widget_free (;25;) (type 5) (param i32 i32))
  (func $__wbg_reserve_free (;26;) (type 5) (param i32 i32))
  (func $__wbg_upcast_car_to_vehicle (;27;) (type 7) (param i32) (result i32))
  (func $__wbg_upcast_dog_to_animal (;28;) (type 7) (param i32) (result i32))
  (func $__wbg_upcast_garden__derived_to_zoo__base (;29;) (type 7) (param i32) (result i32))
  (func $__wbg_upcast_reserve_to_wild__habitat (;30;) (type 7) (param i32) (result i32))
  (func $__wbg_vehicle_free (;31;) (type 5) (param i32 i32))
  (func $__wbg_wild__habitat_free (;32;) (type 5) (param i32 i32))
  (func $__wbg_zoo__base_free (;33;) (type 5) (param i32 i32))
  (func $animal_legs (;34;) (type 7) (param i32) (result i32))
  (func $animal_new (;35;) (type 7) (param i32) (result i32))
  (func $car_doors (;36;) (type 7) (param i32) (result i32))
  (func $car_new (;37;) (type 4) (param i32 i32) (result i32))
  (func $dog_breed (;38;) (type 7) (param i32) (result i32))
  (func $dog_new (;39;) (type 4) (param i32 i32) (result i32))
  (func $garden__derived_new (;40;) (type 4) (param i32 i32) (result i32))
  (func $garden__derived_tag (;41;) (type 7) (param i32) (result i32))
  (func $"makeAnimal externref shim" (;42;) (type 6) (param i32) (result externref))
  (func $"makeBase externref shim" (;43;) (type 6) (param i32) (result externref))
  (func $"makeCar externref shim" (;44;) (type 3) (param i32 i32) (result externref))
  (func $"makeDerived externref shim" (;45;) (type 3) (param i32 i32) (result externref))
  (func $"makeDog externref shim" (;46;) (type 3) (param i32 i32) (result externref))
  (func $"makeHabitat externref shim" (;47;) (type 6) (param i32) (result externref))
  (func $"makeReserve externref shim" (;48;) (type 3) (param i32 i32) (result externref))
  (func $"makeVehicle externref shim" (;49;) (type 6) (param i32) (result externref))
  (func $"makeWidget externref shim" (;50;) (type 6) (param i32) (result externref))
  (func $nsa__widget_new (;51;) (type 7) (param i32) (result i32))
  (func $nsa__widget_v (;52;) (type 7) (param i32) (result i32))
  (func $readAnimals (;53;) (type 4) (param i32 i32) (result i32))
  (func $readBases (;54;) (type 4) (param i32 i32) (result i32))
  (func $readCars (;55;) (type 4) (param i32 i32) (result i32))
  (func $readDeriveds (;56;) (type 4) (param i32 i32) (result i32))
  (func $readDog (;57;) (type 7) (param i32) (result i32))
  (func $readDogs (;58;) (type 4) (param i32 i32) (result i32))
  (func $readHabitats (;59;) (type 4) (param i32 i32) (result i32))
  (func $readReserves (;60;) (type 4) (param i32 i32) (result i32))
  (func $readVehicles (;61;) (type 4) (param i32 i32) (result i32))
  (func $readWidget (;62;) (type 7) (param i32) (result i32))
  (func $readWidgets (;63;) (type 4) (param i32 i32) (result i32))
  (func $reserve_new (;64;) (type 4) (param i32 i32) (result i32))
  (func $reserve_rangers (;65;) (type 7) (param i32) (result i32))
  (func $vehicle_new (;66;) (type 7) (param i32) (result i32))
  (func $vehicle_wheels (;67;) (type 7) (param i32) (result i32))
  (func $wild__habitat_area (;68;) (type 7) (param i32) (result i32))
  (func $wild__habitat_new (;69;) (type 7) (param i32) (result i32))
  (func $zoo__base_id (;70;) (type 7) (param i32) (result i32))
  (func $zoo__base_new (;71;) (type 7) (param i32) (result i32))
  (func $__wbindgen_malloc (;72;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;73;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func $__externref_table_alloc (;74;) (type 8) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
