(module $exported_class_rename_wrap_reftest.wasm
  (type (;0;) (func (param externref) (result i32)))
  (type (;1;) (func (param i32 externref)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32) (result i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32) (result externref)))
  (type (;6;) (func (param i32) (result i32)))
  (type (;7;) (func (result i32)))
  (type (;8;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_edece8177ad01481" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c31b086c2b26051" (func (;1;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_renamed_new" (func (;2;) (type 5)))
  (import "./reference_test_bg.js" "__wbg_renamed_unwrap" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;4;) (type 8)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_renamed_free" (func $__wbg_renamed_free))
  (export "makeRenamed" (func $"makeRenamed externref shim"))
  (export "readRenameds" (func $readRenameds))
  (export "renamed_new" (func $renamed_new))
  (export "renamed_value" (func $renamed_value))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_start" (func 4))
  (func $__wbg_renamed_free (;5;) (type 4) (param i32 i32))
  (func $"makeRenamed externref shim" (;6;) (type 5) (param i32) (result externref))
  (func $readRenameds (;7;) (type 3) (param i32 i32) (result i32))
  (func $renamed_new (;8;) (type 6) (param i32) (result i32))
  (func $renamed_value (;9;) (type 6) (param i32) (result i32))
  (func $__wbindgen_malloc (;10;) (type 3) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;11;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func $__externref_table_alloc (;12;) (type 7) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
