(module $exported_class_rename_collision_reftest.wasm
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_344f42d3211c4765" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 2)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_barpoint_free" (func $__wbg_barpoint_free))
  (export "__wbg_foopoint_free" (func $__wbg_foopoint_free))
  (export "barpoint_new" (func $barpoint_new))
  (export "barpoint_y" (func $barpoint_y))
  (export "foopoint_new" (func $foopoint_new))
  (export "foopoint_x" (func $foopoint_x))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_barpoint_free (;2;) (type 0) (param i32 i32))
  (func $__wbg_foopoint_free (;3;) (type 0) (param i32 i32))
  (func $barpoint_new (;4;) (type 1) (param i32) (result i32))
  (func $barpoint_y (;5;) (type 1) (param i32) (result i32))
  (func $foopoint_new (;6;) (type 1) (param i32) (result i32))
  (func $foopoint_x (;7;) (type 1) (param i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
