(module $exported_class_rename_wrap_reftest.wasm
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func (param i32) (result externref)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c31b086c2b26051" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_renamed_new" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;2;) (type 3)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_renamed_free" (func $__wbg_renamed_free))
  (export "makeRenamed" (func $"makeRenamed externref shim"))
  (export "renamed_new" (func $renamed_new))
  (export "renamed_value" (func $renamed_value))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 2))
  (func $__wbg_renamed_free (;3;) (type 0) (param i32 i32))
  (func $"makeRenamed externref shim" (;4;) (type 1) (param i32) (result externref))
  (func $renamed_new (;5;) (type 2) (param i32) (result i32))
  (func $renamed_value (;6;) (type 2) (param i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
