(module $extends_rust_reftest.wasm
  (type (;0;) (func (param i32 i32 i32 i32 i32 i32) (result i32)))
  (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32 i32)))
  (type (;3;) (func (param i32 i32) (result i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32) (result i32 i32)))
  (type (;6;) (func (param i32) (result i32)))
  (type (;7;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c75d47bf9e7731e" (func (;0;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 7)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_inheritancechild_free" (func $__wbg_inheritancechild_free))
  (export "__wbg_inheritancegrandchild_free" (func $__wbg_inheritancegrandchild_free))
  (export "__wbg_inheritanceparent_free" (func $__wbg_inheritanceparent_free))
  (export "__wbg_ns__nschild_free" (func $__wbg_ns__nschild_free))
  (export "__wbg_ns__nsparent_free" (func $__wbg_ns__nsparent_free))
  (export "__wbg_upcast_inheritancechild_to_inheritanceparent" (func $__wbg_upcast_inheritancechild_to_inheritanceparent))
  (export "__wbg_upcast_inheritancegrandchild_to_inheritancechild" (func $__wbg_upcast_inheritancegrandchild_to_inheritancechild))
  (export "__wbg_upcast_ns__nschild_to_nsparent" (func $__wbg_upcast_ns__nschild_to_nsparent))
  (export "inheritance_borrow_parent" (func $"inheritance_borrow_parent multivalue shim"))
  (export "inheritancechild_extra" (func $"inheritancechild_extra multivalue shim"))
  (export "inheritancechild_new" (func $inheritancechild_new))
  (export "inheritancegrandchild_new" (func $inheritancegrandchild_new))
  (export "inheritancegrandchild_tag" (func $"inheritancegrandchild_tag multivalue shim"))
  (export "inheritanceparent_name" (func $"inheritanceparent_name multivalue shim"))
  (export "inheritanceparent_new" (func $inheritanceparent_new))
  (export "nschild_new" (func $nschild_new))
  (export "nschild_note" (func $"nschild_note multivalue shim"))
  (export "nsparent_label" (func $"nsparent_label multivalue shim"))
  (export "nsparent_new" (func $nsparent_new))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_inheritancechild_free (;2;) (type 4) (param i32 i32))
  (func $__wbg_inheritancegrandchild_free (;3;) (type 4) (param i32 i32))
  (func $__wbg_inheritanceparent_free (;4;) (type 4) (param i32 i32))
  (func $__wbg_ns__nschild_free (;5;) (type 4) (param i32 i32))
  (func $__wbg_ns__nsparent_free (;6;) (type 4) (param i32 i32))
  (func $__wbg_upcast_inheritancechild_to_inheritanceparent (;7;) (type 6) (param i32) (result i32))
  (func $__wbg_upcast_inheritancegrandchild_to_inheritancechild (;8;) (type 6) (param i32) (result i32))
  (func $__wbg_upcast_ns__nschild_to_nsparent (;9;) (type 6) (param i32) (result i32))
  (func $"inheritance_borrow_parent multivalue shim" (;10;) (type 5) (param i32) (result i32 i32))
  (func $"inheritancechild_extra multivalue shim" (;11;) (type 5) (param i32) (result i32 i32))
  (func $inheritancechild_new (;12;) (type 1) (param i32 i32 i32 i32) (result i32))
  (func $inheritancegrandchild_new (;13;) (type 0) (param i32 i32 i32 i32 i32 i32) (result i32))
  (func $"inheritancegrandchild_tag multivalue shim" (;14;) (type 5) (param i32) (result i32 i32))
  (func $"inheritanceparent_name multivalue shim" (;15;) (type 5) (param i32) (result i32 i32))
  (func $inheritanceparent_new (;16;) (type 3) (param i32 i32) (result i32))
  (func $nschild_new (;17;) (type 1) (param i32 i32 i32 i32) (result i32))
  (func $"nschild_note multivalue shim" (;18;) (type 5) (param i32) (result i32 i32))
  (func $"nsparent_label multivalue shim" (;19;) (type 5) (param i32) (result i32 i32))
  (func $nsparent_new (;20;) (type 3) (param i32 i32) (result i32))
  (func $__wbindgen_free (;21;) (type 2) (param i32 i32 i32))
  (func $__wbindgen_malloc (;22;) (type 3) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;23;) (type 1) (param i32 i32 i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
