(module $hooks_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 i32) (result i32)))
  (type (;4;) (func (param i32 i32) (result i32 i32)))
  (type (;5;) (func (param i32 i32 i32)))
  (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_6ddd609b62940d55" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "get_counter" (func $get_counter))
  (export "greet" (func $"greet multivalue shim"))
  (export "__wbg_my_post_reinit" (func $my_post_reinit))
  (export "__wbg_my_pre_reinit" (func $my_pre_reinit))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 1))
  (func $get_counter (;2;) (type 1) (result i32))
  (func $"greet multivalue shim" (;3;) (type 4) (param i32 i32) (result i32 i32))
  (func $my_post_reinit (;4;) (type 0))
  (func $my_pre_reinit (;5;) (type 0))
  (func $__wbindgen_malloc (;6;) (type 3) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;7;) (type 6) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;8;) (type 5) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
