(module $import_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result i32 i32)))
  (type (;3;) (func (result f64)))
  (type (;4;) (func (param i32)))
  (type (;5;) (func (param i32) (result externref)))
  (type (;6;) (func (param i32 i32)))
  (type (;7;) (func (param f64 f64) (result f64)))
  (type (;8;) (func (param externref) (result i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_83ebd457a191bc2a" (func (;0;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_catch_me_687c8ac1b7535045" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_get_b0096ab6db85c3a1" (func (;2;) (type 8)))
  (import "./reference_test_bg.js" "__wbg_my_function_d6c76e66f4e6751a" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_new_625e056221ff6a6e" (func (;4;) (type 5)))
  (import "./reference_test_bg.js" "__wbg_no_catch_be4131677910f8cc" (func (;5;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_reload_cbb85f596c80d974" (func (;6;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_CONST_85b96acb48be57e1" (func (;7;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_write_1411fb0c6d3ebc7b" (func (;8;) (type 6)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;9;) (type 0)))
  (import "./snippets/import_reftest-a82831e16a4c30f1/inline0.js" "add" (func (;10;) (type 7)))
  (import "foo-raw" "bar_from_foo_raw" (func (;11;) (type 0)))
  (import "pure-extern" "extern_fn" (func (;12;) (type 0)))
  (import "tests/wasm/imports.js" "bar_from_foo" (func (;13;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $"exported multivalue shim"))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_dealloc" (func $__externref_table_dealloc))
  (export "__wbindgen_start" (func 9))
  (func $"exported multivalue shim" (;14;) (type 2) (result i32 i32))
  (func $__wbindgen_exn_store (;15;) (type 4) (param i32))
  (func $__externref_table_alloc (;16;) (type 1) (result i32))
  (func $__externref_table_dealloc (;17;) (type 4) (param i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
