(module $inline_js_shim_key_reftest.wasm
  (type (;0;) (func (param i32 externref)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (result i32)))
  (type (;4;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_number_get_2e0e7dee9f701a71" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_41e9ee4f547fc59a" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_X_b08eaf5295bd0096" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_X_f7c456555813532e" (func (;3;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;4;) (type 4)))
  (import "./snippets/inline_js_shim_key_reftest-e174048be1be8309/inline0.js" "get" (func (;5;) (type 3)))
  (import "./snippets/inline_js_shim_key_reftest-e174048be1be8309/inline1.js" "get" (func (;6;) (type 3)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "read" (func $read))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 4))
  (func $read (;7;) (type 3) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
