(module $inspectable_reftest.wasm
  (type (;0;) (func (param i32 i32) (result i32)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_5d9e815e6fdf150f" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 3)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_get_pair_0" (func $__wbg_get_pair_0))
  (export "__wbg_get_pair_1" (func $__wbg_get_pair_1))
  (export "__wbg_get_point_x" (func $__wbg_get_point_x))
  (export "__wbg_get_point_y" (func $__wbg_get_point_y))
  (export "__wbg_pair_free" (func $__wbg_pair_free))
  (export "__wbg_point_free" (func $__wbg_point_free))
  (export "__wbg_set_pair_0" (func $__wbg_set_pair_0))
  (export "__wbg_set_pair_1" (func $__wbg_set_pair_1))
  (export "__wbg_set_point_x" (func $__wbg_set_point_x))
  (export "__wbg_set_point_y" (func $__wbg_set_point_y))
  (export "pair_new" (func $pair_new))
  (export "point_new" (func $point_new))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_get_pair_0 (;2;) (type 2) (param i32) (result i32))
  (func $__wbg_get_pair_1 (;3;) (type 2) (param i32) (result i32))
  (func $__wbg_get_point_x (;4;) (type 2) (param i32) (result i32))
  (func $__wbg_get_point_y (;5;) (type 2) (param i32) (result i32))
  (func $__wbg_pair_free (;6;) (type 1) (param i32 i32))
  (func $__wbg_point_free (;7;) (type 1) (param i32 i32))
  (func $__wbg_set_pair_0 (;8;) (type 1) (param i32 i32))
  (func $__wbg_set_pair_1 (;9;) (type 1) (param i32 i32))
  (func $__wbg_set_point_x (;10;) (type 1) (param i32 i32))
  (func $__wbg_set_point_y (;11;) (type 1) (param i32 i32))
  (func $pair_new (;12;) (type 0) (param i32 i32) (result i32))
  (func $point_new (;13;) (type 0) (param i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
