(module $js_namespace_shim_key_reftest.wasm
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func))
  (import "./reference_test_bg.js" "__wbg_c_c6c4f07d196bdffe" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_c_ca0c67a358a3ed69" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_log_5e5e4051c9e253ff" (func (;2;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_log_747870ed06c474c8" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_warn_505bf06fa20f48dc" (func (;4;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_warn_ac30e50f7e66848f" (func (;5;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;6;) (type 1)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 6))
  (func $exported (;7;) (type 1))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
