(module $js_namespace_shim_key_reftest.wasm
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func (result externref)))
  (type (;2;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_5d9e815e6fdf150f" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_c_27eb6c8c34a36e09" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_c_62f7c495c0da1f6c" (func (;2;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_info_219b4a73877b158f" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_info_b8c8b37229b5e91d" (func (;4;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_log_aa9c51e79de6434e" (func (;5;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_log_df735e8b40a03464" (func (;6;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_STATE_21acaf98a2b6b7ca" (func (;7;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_STATE_73563c4d96c22122" (func (;8;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_warn_505bf06fa20f48dc" (func (;9;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_warn_74a4944fa727b481" (func (;10;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;11;) (type 2)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 11))
  (func $exported (;12;) (type 2))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
