(module $js_namespace_export_same_name_reftest.wasm
  (type (;0;) (func (param externref) (result i32)))
  (type (;1;) (func (param f64 f64) (result i32)))
  (type (;2;) (func (param f64) (result i32)))
  (type (;3;) (func (param i32 externref)))
  (type (;4;) (func (param i32 f64)))
  (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32 i32) (result i32 i32)))
  (type (;7;) (func (param i32 i32 i32)))
  (type (;8;) (func (param i32 i32) (result i32)))
  (type (;9;) (func (param i32 i32)))
  (type (;10;) (func (param i32) (result externref)))
  (type (;11;) (func (param i32) (result f64)))
  (type (;12;) (func (param i32) (result i32 i32)))
  (type (;13;) (func (param i32) (result i32)))
  (type (;14;) (func (result i32 i32)))
  (type (;15;) (func (result i32)))
  (type (;16;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_07cb72cfcc952e2b" (func (;0;) (type 3)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c75d47bf9e7731e" (func (;1;) (type 9)))
  (import "./reference_test_bg.js" "__wbg_bar__point_new" (func (;2;) (type 10)))
  (import "./reference_test_bg.js" "__wbg_bar__point_unwrap" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_foo__point_new" (func (;4;) (type 10)))
  (import "./reference_test_bg.js" "__wbg_foo__point_unwrap" (func (;5;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;6;) (type 16)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_bar__nested__point_free" (func $__wbg_bar__nested__point_free))
  (export "__wbg_bar__point_free" (func $__wbg_bar__point_free))
  (export "__wbg_bar__reftofoo_free" (func $__wbg_bar__reftofoo_free))
  (export "__wbg_foo__nested__point_free" (func $__wbg_foo__nested__point_free))
  (export "__wbg_foo__point_free" (func $__wbg_foo__point_free))
  (export "__wbg_foo__reftobar_free" (func $__wbg_foo__reftobar_free))
  (export "__wbg_get_bar__nested__point_magnitude" (func $__wbg_get_bar__nested__point_magnitude))
  (export "__wbg_get_bar__point_x" (func $__wbg_get_bar__point_x))
  (export "__wbg_get_bar__point_y" (func $__wbg_get_bar__point_y))
  (export "__wbg_get_foo__nested__point_z" (func $__wbg_get_foo__nested__point_z))
  (export "__wbg_get_foo__point_x" (func $__wbg_get_foo__point_x))
  (export "__wbg_get_point_value" (func $__wbg_get_point_value))
  (export "__wbg_namespaceconsumer_free" (func $__wbg_namespaceconsumer_free))
  (export "__wbg_point_free" (func $__wbg_point_free))
  (export "__wbg_set_bar__nested__point_magnitude" (func $__wbg_set_bar__nested__point_magnitude))
  (export "__wbg_set_bar__point_x" (func $__wbg_set_bar__point_x))
  (export "__wbg_set_bar__point_y" (func $__wbg_set_bar__point_y))
  (export "__wbg_set_foo__nested__point_z" (func $__wbg_set_foo__nested__point_z))
  (export "__wbg_set_foo__point_x" (func $__wbg_set_foo__point_x))
  (export "__wbg_set_point_value" (func $__wbg_set_point_value))
  (export "bar__greet" (func $"bar__greet multivalue shim"))
  (export "barnestedpoint_new" (func $barnestedpoint_new))
  (export "barpoint_new" (func $barpoint_new))
  (export "foo__greet" (func $"foo__greet multivalue shim"))
  (export "foo__nested__deep__Status" (func $"foo__nested__deep__Status multivalue shim"))
  (export "foo__nested__greet" (func $"foo__nested__greet multivalue shim"))
  (export "foonestedpoint_new" (func $foonestedpoint_new))
  (export "foopoint_new" (func $foopoint_new))
  (export "greet" (func $"greet multivalue shim"))
  (export "namespaceconsumer_bar_point" (func $namespaceconsumer_bar_point))
  (export "namespaceconsumer_bar_points" (func $"namespaceconsumer_bar_points multivalue shim"))
  (export "namespaceconsumer_bar_status" (func $namespaceconsumer_bar_status))
  (export "namespaceconsumer_duplicate_bar_points" (func $"namespaceconsumer_duplicate_bar_points multivalue shim"))
  (export "namespaceconsumer_duplicate_foo_points" (func $"namespaceconsumer_duplicate_foo_points multivalue shim"))
  (export "namespaceconsumer_foo_point" (func $namespaceconsumer_foo_point))
  (export "namespaceconsumer_foo_points" (func $"namespaceconsumer_foo_points multivalue shim"))
  (export "namespaceconsumer_foo_status" (func $namespaceconsumer_foo_status))
  (export "namespaceconsumer_new" (func $namespaceconsumer_new))
  (export "namespaceconsumer_next_bar_status" (func $namespaceconsumer_next_bar_status))
  (export "namespaceconsumer_next_foo_status" (func $namespaceconsumer_next_foo_status))
  (export "namespaceconsumer_normalize_bar" (func $namespaceconsumer_normalize_bar))
  (export "namespaceconsumer_rotate_foo" (func $namespaceconsumer_rotate_foo))
  (export "namespaceconsumer_set_bar_point" (func $namespaceconsumer_set_bar_point))
  (export "namespaceconsumer_set_bar_points" (func $namespaceconsumer_set_bar_points))
  (export "namespaceconsumer_set_bar_status" (func $namespaceconsumer_set_bar_status))
  (export "namespaceconsumer_set_foo_point" (func $namespaceconsumer_set_foo_point))
  (export "namespaceconsumer_set_foo_points" (func $namespaceconsumer_set_foo_points))
  (export "namespaceconsumer_set_foo_status" (func $namespaceconsumer_set_foo_status))
  (export "reftobar_bar_point" (func $reftobar_bar_point))
  (export "reftobar_bar_status" (func $reftobar_bar_status))
  (export "reftobar_new" (func $reftobar_new))
  (export "reftobar_reflect_point" (func $reftobar_reflect_point))
  (export "reftobar_reflect_status" (func $reftobar_reflect_status))
  (export "reftobar_set_bar_point" (func $reftobar_set_bar_point))
  (export "reftobar_set_bar_status" (func $reftobar_set_bar_status))
  (export "reftofoo_foo_point" (func $reftofoo_foo_point))
  (export "reftofoo_foo_status" (func $reftofoo_foo_status))
  (export "reftofoo_new" (func $reftofoo_new))
  (export "reftofoo_reflect_point" (func $reftofoo_reflect_point))
  (export "reftofoo_reflect_status" (func $reftofoo_reflect_status))
  (export "reftofoo_set_foo_point" (func $reftofoo_set_foo_point))
  (export "reftofoo_set_foo_status" (func $reftofoo_set_foo_status))
  (export "toplevelpoint_new" (func $toplevelpoint_new))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_start" (func 6))
  (func $__wbg_bar__nested__point_free (;7;) (type 9) (param i32 i32))
  (func $__wbg_bar__point_free (;8;) (type 9) (param i32 i32))
  (func $__wbg_bar__reftofoo_free (;9;) (type 9) (param i32 i32))
  (func $__wbg_foo__nested__point_free (;10;) (type 9) (param i32 i32))
  (func $__wbg_foo__point_free (;11;) (type 9) (param i32 i32))
  (func $__wbg_foo__reftobar_free (;12;) (type 9) (param i32 i32))
  (func $__wbg_get_bar__nested__point_magnitude (;13;) (type 11) (param i32) (result f64))
  (func $__wbg_get_bar__point_x (;14;) (type 11) (param i32) (result f64))
  (func $__wbg_get_bar__point_y (;15;) (type 11) (param i32) (result f64))
  (func $__wbg_get_foo__nested__point_z (;16;) (type 11) (param i32) (result f64))
  (func $__wbg_get_foo__point_x (;17;) (type 11) (param i32) (result f64))
  (func $__wbg_get_point_value (;18;) (type 11) (param i32) (result f64))
  (func $__wbg_namespaceconsumer_free (;19;) (type 9) (param i32 i32))
  (func $__wbg_point_free (;20;) (type 9) (param i32 i32))
  (func $__wbg_set_bar__nested__point_magnitude (;21;) (type 4) (param i32 f64))
  (func $__wbg_set_bar__point_x (;22;) (type 4) (param i32 f64))
  (func $__wbg_set_bar__point_y (;23;) (type 4) (param i32 f64))
  (func $__wbg_set_foo__nested__point_z (;24;) (type 4) (param i32 f64))
  (func $__wbg_set_foo__point_x (;25;) (type 4) (param i32 f64))
  (func $__wbg_set_point_value (;26;) (type 4) (param i32 f64))
  (func $"bar__greet multivalue shim" (;27;) (type 14) (result i32 i32))
  (func $barnestedpoint_new (;28;) (type 2) (param f64) (result i32))
  (func $barpoint_new (;29;) (type 1) (param f64 f64) (result i32))
  (func $"foo__greet multivalue shim" (;30;) (type 14) (result i32 i32))
  (func $"foo__nested__deep__Status multivalue shim" (;31;) (type 14) (result i32 i32))
  (func $"foo__nested__greet multivalue shim" (;32;) (type 14) (result i32 i32))
  (func $foonestedpoint_new (;33;) (type 2) (param f64) (result i32))
  (func $foopoint_new (;34;) (type 2) (param f64) (result i32))
  (func $"greet multivalue shim" (;35;) (type 14) (result i32 i32))
  (func $namespaceconsumer_bar_point (;36;) (type 13) (param i32) (result i32))
  (func $"namespaceconsumer_bar_points multivalue shim" (;37;) (type 12) (param i32) (result i32 i32))
  (func $namespaceconsumer_bar_status (;38;) (type 13) (param i32) (result i32))
  (func $"namespaceconsumer_duplicate_bar_points multivalue shim" (;39;) (type 6) (param i32 i32 i32) (result i32 i32))
  (func $"namespaceconsumer_duplicate_foo_points multivalue shim" (;40;) (type 6) (param i32 i32 i32) (result i32 i32))
  (func $namespaceconsumer_foo_point (;41;) (type 13) (param i32) (result i32))
  (func $"namespaceconsumer_foo_points multivalue shim" (;42;) (type 12) (param i32) (result i32 i32))
  (func $namespaceconsumer_foo_status (;43;) (type 13) (param i32) (result i32))
  (func $namespaceconsumer_new (;44;) (type 5) (param i32 i32 i32 i32) (result i32))
  (func $namespaceconsumer_next_bar_status (;45;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_next_foo_status (;46;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_normalize_bar (;47;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_rotate_foo (;48;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_set_bar_point (;49;) (type 9) (param i32 i32))
  (func $namespaceconsumer_set_bar_points (;50;) (type 7) (param i32 i32 i32))
  (func $namespaceconsumer_set_bar_status (;51;) (type 9) (param i32 i32))
  (func $namespaceconsumer_set_foo_point (;52;) (type 9) (param i32 i32))
  (func $namespaceconsumer_set_foo_points (;53;) (type 7) (param i32 i32 i32))
  (func $namespaceconsumer_set_foo_status (;54;) (type 9) (param i32 i32))
  (func $reftobar_bar_point (;55;) (type 13) (param i32) (result i32))
  (func $reftobar_bar_status (;56;) (type 13) (param i32) (result i32))
  (func $reftobar_new (;57;) (type 8) (param i32 i32) (result i32))
  (func $reftobar_reflect_point (;58;) (type 8) (param i32 i32) (result i32))
  (func $reftobar_reflect_status (;59;) (type 8) (param i32 i32) (result i32))
  (func $reftobar_set_bar_point (;60;) (type 9) (param i32 i32))
  (func $reftobar_set_bar_status (;61;) (type 9) (param i32 i32))
  (func $reftofoo_foo_point (;62;) (type 13) (param i32) (result i32))
  (func $reftofoo_foo_status (;63;) (type 13) (param i32) (result i32))
  (func $reftofoo_new (;64;) (type 8) (param i32 i32) (result i32))
  (func $reftofoo_reflect_point (;65;) (type 8) (param i32 i32) (result i32))
  (func $reftofoo_reflect_status (;66;) (type 8) (param i32 i32) (result i32))
  (func $reftofoo_set_foo_point (;67;) (type 9) (param i32 i32))
  (func $reftofoo_set_foo_status (;68;) (type 9) (param i32 i32))
  (func $toplevelpoint_new (;69;) (type 2) (param f64) (result i32))
  (func $__wbindgen_malloc (;70;) (type 8) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;71;) (type 5) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;72;) (type 7) (param i32 i32 i32))
  (func $__externref_drop_slice (;73;) (type 9) (param i32 i32))
  (func $__externref_table_alloc (;74;) (type 15) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
