(module $js_namespace_export_same_name_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32 i32)))
  (type (;2;) (func (param i32) (result f64)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func (param i32 i32 i32)))
  (type (;5;) (func (param i32 f64)))
  (type (;6;) (func (param f64) (result i32)))
  (type (;7;) (func (param f64 f64) (result i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_6ddd609b62940d55" (func (;0;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_bar__point_free" (func $__wbg_bar__point_free))
  (export "__wbg_foo__point_free" (func $__wbg_foo__point_free))
  (export "__wbg_get_bar__point_x" (func $__wbg_get_bar__point_x))
  (export "__wbg_get_bar__point_y" (func $__wbg_get_bar__point_y))
  (export "__wbg_get_foo__point_x" (func $__wbg_get_foo__point_x))
  (export "__wbg_set_bar__point_x" (func $__wbg_set_bar__point_x))
  (export "__wbg_set_bar__point_y" (func $__wbg_set_bar__point_y))
  (export "__wbg_set_foo__point_x" (func $__wbg_set_foo__point_x))
  (export "bar__greet" (func $"bar__greet multivalue shim"))
  (export "barpoint_new" (func $barpoint_new))
  (export "foo__greet" (func $"foo__greet multivalue shim"))
  (export "foopoint_new" (func $foopoint_new))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_bar__point_free (;2;) (type 3) (param i32 i32))
  (func $__wbg_foo__point_free (;3;) (type 3) (param i32 i32))
  (func $__wbg_get_bar__point_x (;4;) (type 2) (param i32) (result f64))
  (func $__wbg_get_bar__point_y (;5;) (type 2) (param i32) (result f64))
  (func $__wbg_get_foo__point_x (;6;) (type 2) (param i32) (result f64))
  (func $__wbg_set_bar__point_x (;7;) (type 5) (param i32 f64))
  (func $__wbg_set_bar__point_y (;8;) (type 5) (param i32 f64))
  (func $__wbg_set_foo__point_x (;9;) (type 5) (param i32 f64))
  (func $"bar__greet multivalue shim" (;10;) (type 1) (result i32 i32))
  (func $barpoint_new (;11;) (type 7) (param f64 f64) (result i32))
  (func $"foo__greet multivalue shim" (;12;) (type 1) (result i32 i32))
  (func $foopoint_new (;13;) (type 6) (param f64) (result i32))
  (func $__wbindgen_free (;14;) (type 4) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
