(module $js_namespace_export_same_name_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result i32 i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32) (result i32 i32)))
  (type (;5;) (func (param i32) (result f64)))
  (type (;6;) (func (param i32) (result externref)))
  (type (;7;) (func (param i32 i32)))
  (type (;8;) (func (param i32 i32) (result i32)))
  (type (;9;) (func (param i32 i32 i32)))
  (type (;10;) (func (param i32 i32 i32) (result i32 i32)))
  (type (;11;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;12;) (func (param i32 f64)))
  (type (;13;) (func (param i32 externref)))
  (type (;14;) (func (param f64) (result i32)))
  (type (;15;) (func (param f64 f64) (result i32)))
  (type (;16;) (func (param externref) (result i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_ab4b34d23d6778bd" (func (;0;) (type 13)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_6b64449b9b9ed33c" (func (;1;) (type 7)))
  (import "./reference_test_bg.js" "__wbg_bar__point_new" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_bar__point_unwrap" (func (;3;) (type 16)))
  (import "./reference_test_bg.js" "__wbg_foo__point_new" (func (;4;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_foo__point_unwrap" (func (;5;) (type 16)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;6;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo__point_free" (func $__wbg_foo__point_free))
  (export "__wbg_get_foo__point_x" (func $__wbg_get_foo__point_x))
  (export "__wbg_set_foo__point_x" (func $__wbg_set_foo__point_x))
  (export "foopoint_new" (func $foopoint_new))
  (export "__wbg_bar__point_free" (func $__wbg_bar__point_free))
  (export "__wbg_get_bar__point_x" (func $__wbg_get_bar__point_x))
  (export "__wbg_set_bar__point_x" (func $__wbg_set_bar__point_x))
  (export "__wbg_get_bar__point_y" (func $__wbg_get_bar__point_y))
  (export "__wbg_set_bar__point_y" (func $__wbg_set_bar__point_y))
  (export "barpoint_new" (func $barpoint_new))
  (export "foo__greet" (func $"foo__greet multivalue shim"))
  (export "bar__greet" (func $"bar__greet multivalue shim"))
  (export "__wbg_foo__nested__point_free" (func $__wbg_foo__nested__point_free))
  (export "__wbg_get_foo__nested__point_z" (func $__wbg_get_foo__nested__point_z))
  (export "__wbg_set_foo__nested__point_z" (func $__wbg_set_foo__nested__point_z))
  (export "foonestedpoint_new" (func $foonestedpoint_new))
  (export "__wbg_bar__nested__point_free" (func $__wbg_bar__nested__point_free))
  (export "__wbg_get_bar__nested__point_magnitude" (func $__wbg_get_bar__nested__point_magnitude))
  (export "__wbg_set_bar__nested__point_magnitude" (func $__wbg_set_bar__nested__point_magnitude))
  (export "barnestedpoint_new" (func $barnestedpoint_new))
  (export "foo__nested__deep__Status" (func $"foo__nested__deep__Status multivalue shim"))
  (export "foo__nested__greet" (func $"foo__nested__greet multivalue shim"))
  (export "__wbg_foo__reftobar_free" (func $__wbg_foo__reftobar_free))
  (export "reftobar_new" (func $reftobar_new))
  (export "reftobar_bar_point" (func $reftobar_bar_point))
  (export "reftobar_set_bar_point" (func $reftobar_set_bar_point))
  (export "reftobar_bar_status" (func $reftobar_bar_status))
  (export "reftobar_set_bar_status" (func $reftobar_set_bar_status))
  (export "reftobar_reflect_point" (func $reftobar_reflect_point))
  (export "reftobar_reflect_status" (func $reftobar_reflect_status))
  (export "__wbg_bar__reftofoo_free" (func $__wbg_bar__reftofoo_free))
  (export "reftofoo_new" (func $reftofoo_new))
  (export "reftofoo_foo_point" (func $reftofoo_foo_point))
  (export "reftofoo_set_foo_point" (func $reftofoo_set_foo_point))
  (export "reftofoo_foo_status" (func $reftofoo_foo_status))
  (export "reftofoo_set_foo_status" (func $reftofoo_set_foo_status))
  (export "reftofoo_reflect_point" (func $reftofoo_reflect_point))
  (export "reftofoo_reflect_status" (func $reftofoo_reflect_status))
  (export "__wbg_namespaceconsumer_free" (func $__wbg_namespaceconsumer_free))
  (export "namespaceconsumer_new" (func $namespaceconsumer_new))
  (export "namespaceconsumer_foo_point" (func $namespaceconsumer_foo_point))
  (export "namespaceconsumer_set_foo_point" (func $namespaceconsumer_set_foo_point))
  (export "namespaceconsumer_bar_point" (func $namespaceconsumer_bar_point))
  (export "namespaceconsumer_set_bar_point" (func $namespaceconsumer_set_bar_point))
  (export "namespaceconsumer_foo_status" (func $namespaceconsumer_foo_status))
  (export "namespaceconsumer_set_foo_status" (func $namespaceconsumer_set_foo_status))
  (export "namespaceconsumer_bar_status" (func $namespaceconsumer_bar_status))
  (export "namespaceconsumer_set_bar_status" (func $namespaceconsumer_set_bar_status))
  (export "namespaceconsumer_foo_points" (func $"namespaceconsumer_foo_points multivalue shim"))
  (export "namespaceconsumer_set_foo_points" (func $namespaceconsumer_set_foo_points))
  (export "namespaceconsumer_bar_points" (func $"namespaceconsumer_bar_points multivalue shim"))
  (export "namespaceconsumer_set_bar_points" (func $namespaceconsumer_set_bar_points))
  (export "namespaceconsumer_rotate_foo" (func $namespaceconsumer_rotate_foo))
  (export "namespaceconsumer_normalize_bar" (func $namespaceconsumer_normalize_bar))
  (export "namespaceconsumer_next_foo_status" (func $namespaceconsumer_next_foo_status))
  (export "namespaceconsumer_next_bar_status" (func $namespaceconsumer_next_bar_status))
  (export "namespaceconsumer_duplicate_foo_points" (func $"namespaceconsumer_duplicate_foo_points multivalue shim"))
  (export "namespaceconsumer_duplicate_bar_points" (func $"namespaceconsumer_duplicate_bar_points multivalue shim"))
  (export "__wbg_point_free" (func $__wbg_point_free))
  (export "__wbg_get_point_value" (func $__wbg_get_point_value))
  (export "__wbg_set_point_value" (func $__wbg_set_point_value))
  (export "toplevelpoint_new" (func $toplevelpoint_new))
  (export "greet" (func $"greet multivalue shim"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_start" (func 6))
  (func $__wbg_foo__point_free (;7;) (type 7) (param i32 i32))
  (func $__wbg_get_foo__point_x (;8;) (type 5) (param i32) (result f64))
  (func $__wbg_set_foo__point_x (;9;) (type 12) (param i32 f64))
  (func $foopoint_new (;10;) (type 14) (param f64) (result i32))
  (func $__wbg_bar__point_free (;11;) (type 7) (param i32 i32))
  (func $__wbg_get_bar__point_x (;12;) (type 5) (param i32) (result f64))
  (func $__wbg_set_bar__point_x (;13;) (type 12) (param i32 f64))
  (func $__wbg_get_bar__point_y (;14;) (type 5) (param i32) (result f64))
  (func $__wbg_set_bar__point_y (;15;) (type 12) (param i32 f64))
  (func $barpoint_new (;16;) (type 15) (param f64 f64) (result i32))
  (func $"foo__greet multivalue shim" (;17;) (type 2) (result i32 i32))
  (func $"bar__greet multivalue shim" (;18;) (type 2) (result i32 i32))
  (func $__wbg_foo__nested__point_free (;19;) (type 7) (param i32 i32))
  (func $__wbg_get_foo__nested__point_z (;20;) (type 5) (param i32) (result f64))
  (func $__wbg_set_foo__nested__point_z (;21;) (type 12) (param i32 f64))
  (func $foonestedpoint_new (;22;) (type 14) (param f64) (result i32))
  (func $__wbg_bar__nested__point_free (;23;) (type 7) (param i32 i32))
  (func $__wbg_get_bar__nested__point_magnitude (;24;) (type 5) (param i32) (result f64))
  (func $__wbg_set_bar__nested__point_magnitude (;25;) (type 12) (param i32 f64))
  (func $barnestedpoint_new (;26;) (type 14) (param f64) (result i32))
  (func $"foo__nested__deep__Status multivalue shim" (;27;) (type 2) (result i32 i32))
  (func $"foo__nested__greet multivalue shim" (;28;) (type 2) (result i32 i32))
  (func $__wbg_foo__reftobar_free (;29;) (type 7) (param i32 i32))
  (func $reftobar_new (;30;) (type 8) (param i32 i32) (result i32))
  (func $reftobar_bar_point (;31;) (type 3) (param i32) (result i32))
  (func $reftobar_set_bar_point (;32;) (type 7) (param i32 i32))
  (func $reftobar_bar_status (;33;) (type 3) (param i32) (result i32))
  (func $reftobar_set_bar_status (;34;) (type 7) (param i32 i32))
  (func $reftobar_reflect_point (;35;) (type 8) (param i32 i32) (result i32))
  (func $reftobar_reflect_status (;36;) (type 8) (param i32 i32) (result i32))
  (func $__wbg_bar__reftofoo_free (;37;) (type 7) (param i32 i32))
  (func $reftofoo_new (;38;) (type 8) (param i32 i32) (result i32))
  (func $reftofoo_foo_point (;39;) (type 3) (param i32) (result i32))
  (func $reftofoo_set_foo_point (;40;) (type 7) (param i32 i32))
  (func $reftofoo_foo_status (;41;) (type 3) (param i32) (result i32))
  (func $reftofoo_set_foo_status (;42;) (type 7) (param i32 i32))
  (func $reftofoo_reflect_point (;43;) (type 8) (param i32 i32) (result i32))
  (func $reftofoo_reflect_status (;44;) (type 8) (param i32 i32) (result i32))
  (func $__wbg_namespaceconsumer_free (;45;) (type 7) (param i32 i32))
  (func $namespaceconsumer_new (;46;) (type 11) (param i32 i32 i32 i32) (result i32))
  (func $namespaceconsumer_foo_point (;47;) (type 3) (param i32) (result i32))
  (func $namespaceconsumer_set_foo_point (;48;) (type 7) (param i32 i32))
  (func $namespaceconsumer_bar_point (;49;) (type 3) (param i32) (result i32))
  (func $namespaceconsumer_set_bar_point (;50;) (type 7) (param i32 i32))
  (func $namespaceconsumer_foo_status (;51;) (type 3) (param i32) (result i32))
  (func $namespaceconsumer_set_foo_status (;52;) (type 7) (param i32 i32))
  (func $namespaceconsumer_bar_status (;53;) (type 3) (param i32) (result i32))
  (func $namespaceconsumer_set_bar_status (;54;) (type 7) (param i32 i32))
  (func $"namespaceconsumer_foo_points multivalue shim" (;55;) (type 4) (param i32) (result i32 i32))
  (func $namespaceconsumer_set_foo_points (;56;) (type 9) (param i32 i32 i32))
  (func $"namespaceconsumer_bar_points multivalue shim" (;57;) (type 4) (param i32) (result i32 i32))
  (func $namespaceconsumer_set_bar_points (;58;) (type 9) (param i32 i32 i32))
  (func $namespaceconsumer_rotate_foo (;59;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_normalize_bar (;60;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_next_foo_status (;61;) (type 8) (param i32 i32) (result i32))
  (func $namespaceconsumer_next_bar_status (;62;) (type 8) (param i32 i32) (result i32))
  (func $"namespaceconsumer_duplicate_foo_points multivalue shim" (;63;) (type 10) (param i32 i32 i32) (result i32 i32))
  (func $"namespaceconsumer_duplicate_bar_points multivalue shim" (;64;) (type 10) (param i32 i32 i32) (result i32 i32))
  (func $__wbg_point_free (;65;) (type 7) (param i32 i32))
  (func $__wbg_get_point_value (;66;) (type 5) (param i32) (result f64))
  (func $__wbg_set_point_value (;67;) (type 12) (param i32 f64))
  (func $toplevelpoint_new (;68;) (type 14) (param f64) (result i32))
  (func $"greet multivalue shim" (;69;) (type 2) (result i32 i32))
  (func $__wbindgen_malloc (;70;) (type 8) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;71;) (type 11) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;72;) (type 9) (param i32 i32 i32))
  (func $__externref_drop_slice (;73;) (type 7) (param i32 i32))
  (func $__externref_table_alloc (;74;) (type 1) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
