(module $jspi_intrinsics_reftest.wasm
  (type (;0;) (func (param externref) (result externref)))
  (type (;1;) (func (param i32 externref)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32) (result externref)))
  (type (;4;) (func (param i32) (result i32)))
  (type (;5;) (func (param i32)))
  (type (;6;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_cleanup_485cc4f59821d0c3" (func (;0;) (type 5)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_get_resolved_ae482262158d0e4e" (func (;1;) (type 3)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_is_rejected_ad8e8b2df7ac1bf8" (func (;2;) (type 4)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_set_pending_eb0737ebb950d87d" (func (;3;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_suspend_a72c0d026c006e17" (func (;4;) (type 5)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_waker_cleanup_e24dd9d90266971f" (func (;5;) (type 5)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_waker_create_ea0ae813d51107c9" (func (;6;) (type 3)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_waker_wake_18ccfe9f06cb07b3" (func (;7;) (type 5)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_344f42d3211c4765" (func (;8;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;9;) (type 6)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "drive" (func $"drive externref shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 9))
  (func $"drive externref shim" (;10;) (type 0) (param externref) (result externref))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
