(module $jspi_reftest.wasm
  (type (;0;) (func (param externref) (result i32)))
  (type (;1;) (func (param i32 externref)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32) (result i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32)))
  (type (;6;) (func (result externref)))
  (type (;7;) (func (result i32)))
  (type (;8;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_41e9ee4f547fc59a" (func (;0;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_fetch_number_5170522aaa809683" (func (;1;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_fetch_text_34534fabe4d1d100" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_sleep_c1b3c1cdf7d71e45" (func (;3;) (type 5)))
  (import "./reference_test_bg.js" "__wbg_try_fetch_8e435833d94a818c" (func (;4;) (type 6)))
  (import "./reference_test_bg.js" "__wbindgen_generic_0000000000000000" (func (;5;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_generic_0000000000000001" (func (;6;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;7;) (type 8)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "compute" (func $"compute jspi wrapper"))
  (export "do_work" (func $"do_work jspi wrapper"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 12))
  (func $"compute jspi wrapper" (;8;) (type 7) (result i32))
  (func $"do_work jspi wrapper" (;9;) (type 8))
  (func $__wbindgen_malloc (;10;) (type 3) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;11;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func (;12;) (type 8))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
