(module $jspi_intrinsics_reftest.wasm
  (type (;0;) (func (param externref) (result externref)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_jspi_suspend_747b367c12c10e32" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_344f42d3211c4765" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_cast_0000000000000000" (func (;2;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 2)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "drive" (func $"drive externref shim jspi wrapper"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 5))
  (func $"drive externref shim jspi wrapper" (;4;) (type 0) (param externref) (result externref))
  (func (;5;) (type 2))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
