// FLAGS: --target=bundler
// FLAGS: --target=no-modules
use wasm_bindgen::prelude::*;

// The JSPI runtime bridge used by `js_sys::futures::jspi` is a single
// suspending intrinsic whose JS body is an identity function:
// `WebAssembly.Suspending` performs the promise resolution itself, resuming
// the fiber with the settled value as the import's externref return value.
// A rejection is thrown into wasm as a `WebAssembly.JSTag` exception, which
// the in-wasm wrapper generated by the CLI catches and records into the
// `__wbindgen_jspi_rejected` linear-memory flag (declared in
// `js_sys::futures::jspi`; mirrored here since this test doesn't link
// js-sys). It is emitted as an intrinsic rather than an `inline_js` snippet
// so that it works with every target — including `--target no-modules`,
// which cannot import from `./snippets/...`.
#[wasm_bindgen(raw_module = "__wbindgen_placeholder__")]
extern "C" {
    #[wasm_bindgen(suspending)]
    fn __wbindgen_jspi_suspend(promise: &JsValue) -> JsValue;
}

#[no_mangle]
pub static mut __wbindgen_jspi_rejected: u32 = 0;

#[wasm_bindgen(jspi)]
pub fn drive(promise: &JsValue) -> JsValue {
    let value = __wbindgen_jspi_suspend(promise);
    if unsafe { __wbindgen_jspi_rejected } != 0 {
        JsValue::NULL
    } else {
        value
    }
}
