(module $jspi_reftest.wasm
  (type (;0;) (func (param i32)))
  (type (;1;) (func (result i32)))
  (type (;2;) (func))
  (import "./reference_test_bg.js" "__wbg_fetch_number_65eabd7e4b01732a" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_sleep_319b371bcbeaac51" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;2;) (type 2)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "compute" (func $compute))
  (export "do_work" (func $do_work))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 2))
  (func $compute (;3;) (type 1) (result i32))
  (func $do_work (;4;) (type 2))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
