(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result externref)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 i32 i32 i32 i32)))
  (type (;4;) (func (param externref)))
  (import "./reference_test_bg.js" "__wbg_new_4b026aaf1c1e4438" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_new_e17dd7c5a1cd57d8" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_let_8d461e9e0592bd8c" (func (;2;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_await_e0a0e75be8b6fef6" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_TRUE_c6b68bf8545d99a3" (func (;4;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_new_d4bfd9add722b492" (func (;5;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_throw" (func (;6;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;7;) (type 0)))
  (func $exported (;8;) (type 0))
  (func $_function (;9;) (type 0))
  (func $_var (;10;) (type 0))
  (func $weird_arguments (;11;) (type 3) (param i32 i32 i32 i32 i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "_function" (func $_function))
  (export "_var" (func $_var))
  (export "weird_arguments" (func $weird_arguments))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 7))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
