(module $keyword_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result externref)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 i32 i32 i32 i32)))
  (type (;4;) (func (param externref)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_dd24417ed36fc46e" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_await_d6a3b8c6a7818623" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_let_6f6af6103d3e2d91" (func (;2;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_new_06a005f0311eb839" (func (;3;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_new_27ac6aec351615ea" (func (;4;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_new_f777371617c89b36" (func (;5;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_TRUE_c4e736fa46a2ab00" (func (;6;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;7;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "_function" (func $_function))
  (export "_var" (func $_var))
  (export "exported" (func $exported))
  (export "weird_arguments" (func $weird_arguments))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 7))
  (func $_function (;8;) (type 0))
  (func $_var (;9;) (type 0))
  (func $exported (;10;) (type 0))
  (func $weird_arguments (;11;) (type 3) (param i32 i32 i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
