(module $modules_reftest.wasm
  (type (;0;) (func (param externref) (result f64)))
  (type (;1;) (func (param i32 i32) (result externref)))
  (type (;2;) (func (param i32 i32) (result f64)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_1506f2235d1bdba0" (func (;0;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_parseFloat_8d725959a008cb49" (func (;1;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_parseFloat_efb706da0845cf8f" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_string_new" (func (;4;) (type 1)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 3))
  (func $exported (;5;) (type 4))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
