(module $modules_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32 i32) (result f64)))
  (type (;3;) (func (param i32 i32) (result externref)))
  (type (;4;) (func (param externref) (result f64)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_dd24417ed36fc46e" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_parseFloat_9247671d3fd29c8d" (func (;1;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_parseFloat_e568a9a7c2403488" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_cast_0000000000000000" (func (;3;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;4;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 4))
  (func $exported (;5;) (type 0))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
