(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32 i32) (result f64)))
  (type (;3;) (func (param i32 i32) (result externref)))
  (type (;4;) (func (param externref) (result f64)))
  (import "./reference_test_bg.js" "__wbg_parseFloat_2be7f01c31025438" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_parseFloat_7bc8aecd47f33642" (func (;1;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_cast_2241b6af4c4b2941" (func (;2;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_throw" (func (;4;) (type 1)))
  (func $exported (;5;) (type 0))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_start" (func 3))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
