(module $optional_args_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (param f64 i32 f64)))
  (type (;2;) (func (param f64 f64 f64)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "all_optional" (func $all_optional))
  (export "some_optional" (func $some_optional))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 0))
  (func $all_optional (;1;) (type 2) (param f64 f64 f64))
  (func $some_optional (;2;) (type 1) (param f64 i32 f64))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
