(module $panic_unwind_reftest.wasm
  (type (;0;) (func (param externref) (result externref)))
  (type (;1;) (func (param externref)))
  (type (;2;) (func (param i32 i32) (result externref)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func (param i32) (result i32)))
  (type (;5;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_panic_error_a4429721aaf96b50" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_rethrow_8e609956a7b9f4fb" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c75d47bf9e7731e" (func (;2;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_cast_0000000000000000" (func (;3;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;4;) (type 5)))
  (table (;0;) 0 funcref)
  (table $__wbindgen_externrefs (;1;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "maybe_panic" (func $maybe_panic))
  (export "__wbindgen_export" (table 0))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 4))
  (func $maybe_panic (;5;) (type 4) (param i32) (result i32))
  (@custom "target_features" (after code) "\09+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\12exception-handling+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
