(module $pointers_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32) (result i32)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "const_pointer" (func $const_pointer))
  (export "mut_pointer" (func $mut_pointer))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 0))
  (func $const_pointer (;1;) (type 1) (param i32) (result i32))
  (func $mut_pointer (;2;) (type 1) (param i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
