(module $private_dedupe_reftest.wasm
  (type (;0;) (func (param i32 i32 i32)))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32) (result externref)))
  (type (;3;) (func (param i32) (result i32 i32)))
  (type (;4;) (func (param i32) (result i32)))
  (type (;5;) (func (result i32 i32)))
  (type (;6;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_bb96b2010945f0bc" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_status2_new" (func (;1;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_status_new" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 6)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_get_status2_code" (func $__wbg_get_status2_code))
  (export "__wbg_get_status_code" (func $__wbg_get_status_code))
  (export "__wbg_set_status2_code" (func $__wbg_set_status2_code))
  (export "__wbg_set_status_code" (func $__wbg_set_status_code))
  (export "__wbg_status2_free" (func $__wbg_status2_free))
  (export "__wbg_status_free" (func $__wbg_status_free))
  (export "status2_describe" (func $"status2_describe multivalue shim"))
  (export "status_describe" (func $"status_describe multivalue shim"))
  (export "statuses" (func $"statuses multivalue shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__wbindgen_start" (func 3))
  (func $__wbg_get_status2_code (;4;) (type 4) (param i32) (result i32))
  (func $__wbg_get_status_code (;5;) (type 4) (param i32) (result i32))
  (func $__wbg_set_status2_code (;6;) (type 1) (param i32 i32))
  (func $__wbg_set_status_code (;7;) (type 1) (param i32 i32))
  (func $__wbg_status2_free (;8;) (type 1) (param i32 i32))
  (func $__wbg_status_free (;9;) (type 1) (param i32 i32))
  (func $"status2_describe multivalue shim" (;10;) (type 3) (param i32) (result i32 i32))
  (func $"status_describe multivalue shim" (;11;) (type 3) (param i32) (result i32 i32))
  (func $"statuses multivalue shim" (;12;) (type 5) (result i32 i32))
  (func $__wbindgen_free (;13;) (type 0) (param i32 i32 i32))
  (func $__externref_drop_slice (;14;) (type 1) (param i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
