(module $private_dedupe_reftest.wasm
  (type (;0;) (func (param f64) (result externref)))
  (type (;1;) (func (param i32 i32 i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32) (result externref)))
  (type (;4;) (func (param i32) (result i32 i32)))
  (type (;5;) (func (param i32) (result i32)))
  (type (;6;) (func (result i32 i32)))
  (type (;7;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_5d9e815e6fdf150f" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_status2_new" (func (;1;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_status_new" (func (;2;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_generic_0000000000000000" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;4;) (type 7)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_get_status2_code" (func $__wbg_get_status2_code))
  (export "__wbg_get_status_code" (func $__wbg_get_status_code))
  (export "__wbg_set_status2_code" (func $__wbg_set_status2_code))
  (export "__wbg_set_status_code" (func $__wbg_set_status_code))
  (export "__wbg_status2_free" (func $__wbg_status2_free))
  (export "__wbg_status_free" (func $__wbg_status_free))
  (export "a_levels" (func $"a_levels multivalue shim"))
  (export "b_levels" (func $"b_levels multivalue shim"))
  (export "b_statuses" (func $"b_statuses multivalue shim"))
  (export "status2_describe" (func $"status2_describe multivalue shim"))
  (export "status_describe" (func $"status_describe multivalue shim"))
  (export "statuses" (func $"statuses multivalue shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 4))
  (func $__wbg_get_status2_code (;5;) (type 5) (param i32) (result i32))
  (func $__wbg_get_status_code (;6;) (type 5) (param i32) (result i32))
  (func $__wbg_set_status2_code (;7;) (type 2) (param i32 i32))
  (func $__wbg_set_status_code (;8;) (type 2) (param i32 i32))
  (func $__wbg_status2_free (;9;) (type 2) (param i32 i32))
  (func $__wbg_status_free (;10;) (type 2) (param i32 i32))
  (func $"a_levels multivalue shim" (;11;) (type 6) (result i32 i32))
  (func $"b_levels multivalue shim" (;12;) (type 6) (result i32 i32))
  (func $"b_statuses multivalue shim" (;13;) (type 6) (result i32 i32))
  (func $"status2_describe multivalue shim" (;14;) (type 4) (param i32) (result i32 i32))
  (func $"status_describe multivalue shim" (;15;) (type 4) (param i32) (result i32 i32))
  (func $"statuses multivalue shim" (;16;) (type 6) (result i32 i32))
  (func $__externref_drop_slice (;17;) (type 2) (param i32 i32))
  (func $__wbindgen_free (;18;) (type 1) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
