(module $private_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_83ebd457a191bc2a" (func (;0;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_get_hiddenstruct_value" (func $__wbg_get_hiddenstruct_value))
  (export "__wbg_get_namespacedhidden_data" (func $__wbg_get_namespacedhidden_data))
  (export "__wbg_get_publicstruct_value" (func $__wbg_get_publicstruct_value))
  (export "__wbg_hiddenstruct_free" (func $__wbg_hiddenstruct_free))
  (export "__wbg_namespacedhidden_free" (func $__wbg_namespacedhidden_free))
  (export "__wbg_publicstruct_free" (func $__wbg_publicstruct_free))
  (export "__wbg_set_hiddenstruct_value" (func $__wbg_set_hiddenstruct_value))
  (export "__wbg_set_namespacedhidden_data" (func $__wbg_set_namespacedhidden_data))
  (export "__wbg_set_publicstruct_value" (func $__wbg_set_publicstruct_value))
  (export "get_public_struct" (func $get_public_struct))
  (export "internal_create_namespaced" (func $internal_create_namespaced))
  (export "use_hidden_enum" (func $use_hidden_enum))
  (export "use_hidden_struct" (func $use_hidden_struct))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_get_hiddenstruct_value (;2;) (type 2) (param i32) (result i32))
  (func $__wbg_get_namespacedhidden_data (;3;) (type 2) (param i32) (result i32))
  (func $__wbg_get_publicstruct_value (;4;) (type 2) (param i32) (result i32))
  (func $__wbg_hiddenstruct_free (;5;) (type 3) (param i32 i32))
  (func $__wbg_namespacedhidden_free (;6;) (type 3) (param i32 i32))
  (func $__wbg_publicstruct_free (;7;) (type 3) (param i32 i32))
  (func $__wbg_set_hiddenstruct_value (;8;) (type 3) (param i32 i32))
  (func $__wbg_set_namespacedhidden_data (;9;) (type 3) (param i32 i32))
  (func $__wbg_set_publicstruct_value (;10;) (type 3) (param i32 i32))
  (func $get_public_struct (;11;) (type 1) (result i32))
  (func $internal_create_namespaced (;12;) (type 1) (result i32))
  (func $use_hidden_enum (;13;) (type 2) (param i32) (result i32))
  (func $use_hidden_struct (;14;) (type 2) (param i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
