(module $raw_reftest.wasm
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func))
  (type (;3;) (func (result externref)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_6ddd609b62940d55" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 2)))
  (import "test" "test2" (func (;2;) (type 3)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_test_free" (func $__wbg_test_free))
  (export "test1" (func $test1))
  (export "test_test1" (func $test_test1))
  (export "test_test2" (func $test_test2))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_test_free (;3;) (type 0) (param i32 i32))
  (func $test1 (;4;) (type 1) (param i32) (result i32))
  (func $test_test1 (;5;) (type 1) (param i32) (result i32))
  (func $test_test2 (;6;) (type 0) (param i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
