(module $reserved_class_name_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_83ebd457a191bc2a" (func (;0;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_new_b111a190b215eaf0" (func (;1;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;2;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_array_free" (func $__wbg_array_free))
  (export "array_get" (func $array_get))
  (export "array_new" (func $array_new))
  (export "use_js_array" (func $"use_js_array externref shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 2))
  (func $__wbg_array_free (;3;) (type 4) (param i32 i32))
  (func $array_get (;4;) (type 3) (param i32) (result i32))
  (func $array_new (;5;) (type 1) (result i32))
  (func $"use_js_array externref shim" (;6;) (type 2) (result externref))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
