(module $scalar_ref_args_reftest.wasm
  (type (;0;) (func (param f32 f64 i32 i32)))
  (type (;1;) (func (param i32 i32 i32 i64 i64 i64 i32)))
  (type (;2;) (func (result i32)))
  (type (;3;) (func))
  (import "./reference_test_bg.js" "__wbg_takeOtherRefs_ac11064eb438d124" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_takeSignedRefs_403fd2c6a03e5f9e" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_takeUnsignedRefs_ed8a3712ea2f6657" (func (;2;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 3)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "driver" (func $driver))
  (export "return_scalar_ref_via_alias" (func $return_scalar_ref_via_alias))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 3))
  (func $driver (;4;) (type 3))
  (func $return_scalar_ref_via_alias (;5;) (type 2) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
