(module $self_type_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_83ebd457a191bc2a" (func (;0;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_test_free" (func $__wbg_test_free))
  (export "test_consume_self" (func $test_consume_self))
  (export "test_new" (func $test_new))
  (export "test_ref_mut_self" (func $test_ref_mut_self))
  (export "test_ref_self" (func $test_ref_self))
  (export "test_self_Self" (func $test_self_Self))
  (export "test_self_ref_Self" (func $test_self_ref_Self))
  (export "test_self_ref_mut_Self" (func $test_self_ref_mut_Self))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $__wbg_test_free (;2;) (type 3) (param i32 i32))
  (func $test_consume_self (;3;) (type 2) (param i32))
  (func $test_new (;4;) (type 1) (result i32))
  (func $test_ref_mut_self (;5;) (type 2) (param i32))
  (func $test_ref_self (;6;) (type 2) (param i32))
  (func $test_self_Self (;7;) (type 2) (param i32))
  (func $test_self_ref_Self (;8;) (type 2) (param i32))
  (func $test_self_ref_mut_Self (;9;) (type 2) (param i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
