(module $slice_to_array_reftest.wasm
  (type (;0;) (func (param i32 i32 i32)))
  (type (;1;) (func (param i32 i32) (result externref)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_1506f2235d1bdba0" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_js_block_slice_u16_4f2e50bc26aab9e1" (func (;1;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_js_slice_optional_u16_as_array_57dd5435097afce2" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_js_slice_string_as_array_fc6d35fea48d3225" (func (;3;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_js_slice_u16_as_array_f3ff7d1fa16fa117" (func (;4;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;5;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_string_new" (func (;6;) (type 1)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "driver" (func $driver))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_drop_slice" (func $__externref_drop_slice))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 5))
  (func $driver (;7;) (type 3))
  (func $__externref_drop_slice (;8;) (type 2) (param i32 i32))
  (func $__wbindgen_free (;9;) (type 0) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
