(module $slice_args_debug_reftest.wasm
  (type (;0;) (func (param i32 i32 externref)))
  (type (;1;) (func (param i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (result i32)))
  (type (;5;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_copy_to_typed_array_88899a52af046901" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_41e9ee4f547fc59a" (func (;1;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_get_bytes_7b68a3d437466926" (func (;2;) (type 3)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 5)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "call_get_bytes" (func $call_get_bytes))
  (export "take_boxed_slice" (func $take_boxed_slice))
  (export "take_clamped" (func $take_clamped))
  (export "take_jsvalue_vec" (func $take_jsvalue_vec))
  (export "take_mut_slice" (func $"take_mut_slice externref shim"))
  (export "take_optional_vec" (func $take_optional_vec))
  (export "take_slice" (func $take_slice))
  (export "take_vec" (func $take_vec))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_start" (func 3))
  (func $call_get_bytes (;4;) (type 4) (result i32))
  (func $take_boxed_slice (;5;) (type 2) (param i32 i32))
  (func $take_clamped (;6;) (type 2) (param i32 i32))
  (func $take_jsvalue_vec (;7;) (type 2) (param i32 i32))
  (func $"take_mut_slice externref shim" (;8;) (type 0) (param i32 i32 externref))
  (func $take_optional_vec (;9;) (type 2) (param i32 i32))
  (func $take_slice (;10;) (type 2) (param i32 i32))
  (func $take_vec (;11;) (type 2) (param i32 i32))
  (func $__wbindgen_malloc (;12;) (type 1) (param i32 i32) (result i32))
  (func $__externref_table_alloc (;13;) (type 4) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
