(module $static_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (param i32 i32)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_f1861aae416df39d" (func (;0;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_NAMESPACE_OPTIONAL_2e93032090b95d76" (func (;1;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_NAMESPACE_PLAIN_996cfe92d41df43c" (func (;2;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_NESTED_NAMESPACE_OPTIONAL_c736ff66b2fdaa43" (func (;3;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_NESTED_NAMESPACE_PLAIN_e9affde7bc139ebd" (func (;4;) (type 2)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_OPTIONAL_8c4485fd717985fd" (func (;5;) (type 1)))
  (import "./reference_test_bg.js" "__wbg_static_accessor_PLAIN_c0ea7240f2fd9157" (func (;6;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;7;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "exported" (func $exported))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 7))
  (func $exported (;8;) (type 0))
  (func $__externref_table_alloc (;9;) (type 1) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
