(module $string_from_utf8_lossy_reftest.wasm
  (type (;0;) (func (param i32 i32) (result externref)))
  (type (;1;) (func (param i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_string_from_utf8_lossy_da861c7d40e6c311" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_41e9ee4f547fc59a" (func (;1;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;2;) (type 3)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "foo" (func $"foo externref shim"))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_start" (func 2))
  (func $"foo externref shim" (;3;) (type 0) (param i32 i32) (result externref))
  (func $__wbindgen_malloc (;4;) (type 1) (param i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
