(module $symbol_reftest.wasm
  (type (;0;) (func (param externref) (result i32)))
  (type (;1;) (func (param i32 externref)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32)))
  (type (;6;) (func (param i32) (result i32 i32)))
  (type (;7;) (func (result externref)))
  (type (;8;) (func))
  (import "./reference_test_bg.js" "__wbg_Symbol_iterator_9a3ae6c7dad7d3ed" (func (;0;) (type 0)))
  (import "./reference_test_bg.js" "__wbg_Symbol_toPrimitive_4bd6ba9d43ef2762" (func (;1;) (type 5)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_9c75d47bf9e7731e" (func (;2;) (type 5)))
  (import "./reference_test_bg.js" "__wbg_import_static_symbol_getter_00eaaec525eefd39" (func (;3;) (type 8)))
  (import "./reference_test_bg.js" "__wbg_new_40230a3912a25f41" (func (;4;) (type 7)))
  (import "./reference_test_bg.js" "__wbg_string_getter_792c0b754030f0c6" (func (;5;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;6;) (type 8)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "foo_Symbol_toPrimitive" (func $"foo_Symbol_toPrimitive multivalue shim"))
  (export "foo_to_string_tag" (func $"foo_to_string_tag multivalue shim"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 6))
  (func $__wbg_foo_free (;7;) (type 5) (param i32 i32))
  (func $"foo_Symbol_toPrimitive multivalue shim" (;8;) (type 6) (param i32) (result i32 i32))
  (func $"foo_to_string_tag multivalue shim" (;9;) (type 6) (param i32) (result i32 i32))
  (func $__wbindgen_malloc (;10;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;11;) (type 2) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;12;) (type 3) (param i32 i32 i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
