(module $targets_reftest_atomics.wasm
  (type (;0;) (func))
  (type (;1;) (func (result f64)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32 i32)))
  (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;7;) (func (param i32 externref)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_0bc8482c6e3508ae" (func (;0;) (type 7)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_be289d5034ed271b" (func (;1;) (type 3)))
  (import "./reference_test_bg.js" "__wbg_random_e2b253f0e987bd7c" (func (;2;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 0)))
  (import "./reference_test_bg.js" "memory" (memory (;0;) 18 16384 shared))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (export "add_that_might_fail" (func $add_that_might_fail))
  (export "memory" (memory 0))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_thread_destroy" (func $__wbindgen_thread_destroy))
  (export "__wbindgen_start" (func 8))
  (func $add_that_might_fail (;4;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_malloc (;5;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;6;) (type 6) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_thread_destroy (;7;) (type 5) (param i32 i32 i32))
  (func (;8;) (type 2) (param i32))
  (@custom "target_features" (after code) "\09+\07atomics+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
