(module $targets_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result f64)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32 i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32 i32)))
  (import "__wbindgen_placeholder__" "__wbg_random_0000000000000000" (func (;0;) (type 1)))
  (import "__wbindgen_placeholder__" "__wbg_wbindgenthrow_0000000000000001" (func (;1;) (type 3)))
  (import "__wbindgen_placeholder__" "__wbindgen_init_externref_table" (func (;2;) (type 0)))
  (import "wbg" "memory" (memory (;0;) 18 16384 shared))
  (func $add_that_might_fail (;3;) (type 4) (param i32 i32) (result i32))
  (func $__wbindgen_thread_destroy (;4;) (type 5) (param i32 i32 i32))
  (func (;5;) (type 2) (param i32))
  (table (;0;) 128 externref)
  (export "add_that_might_fail" (func $add_that_might_fail))
  (export "memory" (memory 0))
  (export "__wbindgen_export_1" (table 0))
  (export "__wbindgen_thread_destroy" (func $__wbindgen_thread_destroy))
  (export "__wbindgen_start" (func 5))
  (@custom "target_features" (after code) "\09+\07atomics+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
