(module $targets_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result f64)))
  (type (;2;) (func (param i32 i32) (result i32)))
  (import "./reference_test_bg.js" "__wbg_random_fcf922927450bad6" (func (;0;) (type 1)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "add_that_might_fail" (func $add_that_might_fail))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 1))
  (func $add_that_might_fail (;2;) (type 2) (param i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
