(module $typescript_type_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 i32) (result i32)))
  (type (;4;) (func (param externref)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_f1861aae416df39d" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "single" (func $"single externref shim"))
  (export "slice" (func $slice))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_start" (func 1))
  (func $"single externref shim" (;2;) (type 4) (param externref))
  (func $slice (;3;) (type 2) (param i32 i32))
  (func $__externref_table_alloc (;4;) (type 1) (result i32))
  (func $__wbindgen_malloc (;5;) (type 3) (param i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
