(module $typescript_type_reftest.wasm
  (type (;0;) (func (param externref)))
  (type (;1;) (func (param i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (result i32)))
  (type (;5;) (func))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_bb96b2010945f0bc" (func (;0;) (type 2)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 5)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "accented" (func $"accented externref shim"))
  (export "single" (func $"single externref shim"))
  (export "slice" (func $slice))
  (export "take_cafe" (func $take_cafe))
  (export "take_groesse" (func $take_groesse))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_start" (func 1))
  (func $"accented externref shim" (;2;) (type 0) (param externref))
  (func $"single externref shim" (;3;) (type 0) (param externref))
  (func $slice (;4;) (type 2) (param i32 i32))
  (func $take_cafe (;5;) (type 3) (param i32) (result i32))
  (func $take_groesse (;6;) (type 3) (param i32) (result i32))
  (func $__externref_table_alloc (;7;) (type 4) (result i32))
  (func $__wbindgen_malloc (;8;) (type 1) (param i32 i32) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
