(module $reference_test.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result i32 i32)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32 i32)))
  (type (;7;) (func (param i32 i32 i32) (result externref)))
  (type (;8;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;9;) (func (param i32 i32 externref)))
  (type (;10;) (func (param i32 i32 externref i32 externref)))
  (type (;11;) (func (param i32 i32 externref externref)))
  (type (;12;) (func (param i32 i64 externref i32 i32) (result i32 i32)))
  (type (;13;) (func (param i64 i64) (result i32 i64 i64)))
  (type (;14;) (func (param externref)))
  (import "wbg" "__wbindgen_init_externref_table" (func (;0;) (type 0)))
  (func $__wbindgen_realloc (;1;) (type 8) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_malloc (;2;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_exn_store (;3;) (type 3) (param i32))
  (func $wasmbindgentestcontext_include_ignored (;4;) (type 4) (param i32 i32))
  (func $wasmbindgentestcontext_filtered_count (;5;) (type 4) (param i32 i32))
  (func $__wbgt__reference_test::example_test (;6;) (type 3) (param i32))
  (func $wasm_bindgen::convert::closures::invoke0_mut::h99d1e3009d33d179 (;7;) (type 4) (param i32 i32))
  (func $__wbindgen_free (;8;) (type 6) (param i32 i32 i32))
  (func $__wbg_wasmbindgentestcontext_free (;9;) (type 4) (param i32 i32))
  (func $wasmbindgentestcontext_new (;10;) (type 1) (result i32))
  (func $"example externref shim multivalue shim" (;11;) (type 12) (param i32 i64 externref i32 i32) (result i32 i32))
  (func $"example_128 multivalue shim" (;12;) (type 13) (param i64 i64) (result i32 i64 i64))
  (func $"__wbgtest_console_log externref shim" (;13;) (type 14) (param externref))
  (func $"__wbgtest_console_debug externref shim" (;14;) (type 14) (param externref))
  (func $"__wbgtest_console_info externref shim" (;15;) (type 14) (param externref))
  (func $"__wbgtest_console_warn externref shim" (;16;) (type 14) (param externref))
  (func $"__wbgtest_console_error externref shim" (;17;) (type 14) (param externref))
  (func $"__wbgtest_cov_dump multivalue shim" (;18;) (type 2) (result i32 i32))
  (func $"closure81 externref shim" (;19;) (type 10) (param i32 i32 externref i32 externref))
  (func $__externref_table_alloc (;20;) (type 1) (result i32))
  (func $"closure65 externref shim" (;21;) (type 11) (param i32 i32 externref externref))
  (func $"wasmbindgentestcontext_run externref shim" (;22;) (type 7) (param i32 i32 i32) (result externref))
  (func $"closure51 externref shim" (;23;) (type 9) (param i32 i32 externref))
  (table (;0;) 128 128 funcref)
  (table (;1;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "example" (func $"example externref shim multivalue shim"))
  (export "example_128" (func $"example_128 multivalue shim"))
  (export "__wbgt__reference_test::example_test" (func $__wbgt__reference_test::example_test))
  (export "__wbgtest_cov_dump" (func $"__wbgtest_cov_dump multivalue shim"))
  (export "__wbg_wasmbindgentestcontext_free" (func $__wbg_wasmbindgentestcontext_free))
  (export "wasmbindgentestcontext_new" (func $wasmbindgentestcontext_new))
  (export "wasmbindgentestcontext_include_ignored" (func $wasmbindgentestcontext_include_ignored))
  (export "wasmbindgentestcontext_filtered_count" (func $wasmbindgentestcontext_filtered_count))
  (export "wasmbindgentestcontext_run" (func $"wasmbindgentestcontext_run externref shim"))
  (export "__wbgtest_console_log" (func $"__wbgtest_console_log externref shim"))
  (export "__wbgtest_console_debug" (func $"__wbgtest_console_debug externref shim"))
  (export "__wbgtest_console_info" (func $"__wbgtest_console_info externref shim"))
  (export "__wbgtest_console_warn" (func $"__wbgtest_console_warn externref shim"))
  (export "__wbgtest_console_error" (func $"__wbgtest_console_error externref shim"))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_export_1" (table 1))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__wbindgen_export_5" (table 0))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "closure51_externref_shim" (func $"closure51 externref shim"))
  (export "wasm_bindgen__convert__closures__invoke0_mut__h99d1e3009d33d179" (func $wasm_bindgen::convert::closures::invoke0_mut::h99d1e3009d33d179))
  (export "closure81_externref_shim" (func $"closure81 externref shim"))
  (export "closure65_externref_shim" (func $"closure65 externref shim"))
  (export "__wbindgen_start" (func 0))
  (@custom "target_features" (after code) "\04+\0amultivalue+\0fmutable-globals+\0freference-types+\08sign-ext")
)

