(module $wasm_export_types_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32)))
  (type (;2;) (func (param i32 i32) (result i32)))
  (type (;3;) (func (param i32 i32 i32)))
  (type (;4;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;5;) (func (param i32 i64 externref i32 i32) (result i32 i32)))
  (type (;6;) (func (param i64 i64) (result i32 i64 i64)))
  (import "wbg" "__wbg_wbindgenthrow_451ec1a8469d7eb6" (func (;0;) (type 1)))
  (import "wbg" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (func $"example externref shim multivalue shim" (;2;) (type 5) (param i32 i64 externref i32 i32) (result i32 i32))
  (func $"example_128 multivalue shim" (;3;) (type 6) (param i64 i64) (result i32 i64 i64))
  (func $__wbindgen_malloc (;4;) (type 2) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;5;) (type 4) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_free (;6;) (type 3) (param i32 i32 i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "example" (func $"example externref shim multivalue shim"))
  (export "example_128" (func $"example_128 multivalue shim"))
  (export "__wbindgen_export_0" (table 0))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_start" (func 1))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
