(module $web_sys_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32) (result externref)))
  (type (;7;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;8;) (func (param i32 externref)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_debug_string_a1b3fd0656850da8" (func (;0;) (type 8)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_83ebd457a191bc2a" (func (;1;) (type 4)))
  (import "./reference_test_bg.js" "__wbg_new_c28d12cd5cd04757" (func (;2;) (type 6)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 1024 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "get_media_source" (func $get_media_source))
  (export "get_url" (func $"get_url externref shim"))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "__wbindgen_start" (func 3))
  (func $get_media_source (;4;) (type 1) (result i32))
  (func $"get_url externref shim" (;5;) (type 2) (result externref))
  (func $__wbindgen_malloc (;6;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;7;) (type 7) (param i32 i32 i32 i32) (result i32))
  (func $__wbindgen_exn_store (;8;) (type 3) (param i32))
  (func $__externref_table_alloc (;9;) (type 1) (result i32))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
