(module $web_sys_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (result externref)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32 i32)))
  (type (;5;) (func (param i32 i32) (result i32)))
  (type (;6;) (func (param i32 i32) (result externref)))
  (type (;7;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;8;) (func (param i32 externref)))
  (import "./reference_test_bg.js" "__wbg_new_5aa0cc5d73961235" (func (;0;) (type 6)))
  (import "./reference_test_bg.js" "__wbg_wbindgendebugstring_bb652b1bc2061b6d" (func (;1;) (type 8)))
  (import "./reference_test_bg.js" "__wbg_wbindgenthrow_4c11a24fca429ccf" (func (;2;) (type 4)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;3;) (type 0)))
  (func $"get_url externref shim" (;4;) (type 2) (result externref))
  (func $get_media_source (;5;) (type 1) (result i32))
  (func $__wbindgen_exn_store (;6;) (type 3) (param i32))
  (func $__externref_table_alloc (;7;) (type 1) (result i32))
  (func $__wbindgen_malloc (;8;) (type 5) (param i32 i32) (result i32))
  (func $__wbindgen_realloc (;9;) (type 7) (param i32 i32 i32 i32) (result i32))
  (table (;0;) 128 externref)
  (memory (;0;) 17)
  (export "memory" (memory 0))
  (export "get_url" (func $"get_url externref shim"))
  (export "get_media_source" (func $get_media_source))
  (export "__wbindgen_exn_store" (func $__wbindgen_exn_store))
  (export "__externref_table_alloc" (func $__externref_table_alloc))
  (export "__wbindgen_export_2" (table 0))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbindgen_start" (func 3))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
