name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    # runs-on: codspeed-macro
    runs-on: ubuntu-latest
    env:
      CODSPEED_PERF_ENABLED: false

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime
          run: ./benchmark.sh
          token: ${{ secrets.CODSPEED_TOKEN }}

